/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UtrechtIconActueel {
    }
    interface UtrechtIconAfval {
    }
    interface UtrechtIconAfvalContainer {
    }
    interface UtrechtIconAfvalOphaal {
    }
    interface UtrechtIconAfvalScheiden {
    }
    interface UtrechtIconAfvalkalender {
    }
    interface UtrechtIconAgenda {
    }
    interface UtrechtIconAirborne {
    }
    interface UtrechtIconAttentie {
    }
    interface UtrechtIconAuto {
    }
    interface UtrechtIconBedrijventerrein {
    }
    interface UtrechtIconBegroting {
    }
    interface UtrechtIconBelastingen {
    }
    interface UtrechtIconBevolking {
    }
    interface UtrechtIconBevrijding {
    }
    interface UtrechtIconBezwaarEnBeroep {
    }
    interface UtrechtIconBijstandsuitkering {
    }
    interface UtrechtIconBladerenOpruimen {
    }
    interface UtrechtIconBouwenEnVerbouwen {
    }
    interface UtrechtIconBrandgevaar {
    }
    interface UtrechtIconBuitengebied {
    }
    interface UtrechtIconComputerregeling {
    }
    interface UtrechtIconContactGemeente {
    }
    interface UtrechtIconContainer {
    }
    interface UtrechtIconDocumenten {
    }
    interface UtrechtIconDuurzaamheid {
    }
    interface UtrechtIconEconomieWerkInkomen {
    }
    interface UtrechtIconEikenprocessie {
    }
    interface UtrechtIconEnergietransitie {
    }
    interface UtrechtIconEvenementen {
    }
    interface UtrechtIconF1 {
    }
    interface UtrechtIconFiets {
    }
    interface UtrechtIconGebruikerCentraal {
    }
    interface UtrechtIconGebruikerIngelogd {
    }
    interface UtrechtIconGebruikersvraag {
    }
    interface UtrechtIconGemeenteraad {
    }
    interface UtrechtIconGemivaLocatie {
    }
    interface UtrechtIconGezicht {
    }
    interface UtrechtIconGladheid {
    }
    interface UtrechtIconGrafiek {
    }
    interface UtrechtIconGrofvuil {
    }
    interface UtrechtIconHondenbelasting {
    }
    interface UtrechtIconHorecavergunningen {
    }
    interface UtrechtIconHuis {
    }
    interface UtrechtIconHuisEnOmgeving {
    }
    interface UtrechtIconHulpmiddelenVinden {
    }
    interface UtrechtIconIdkaart {
    }
    interface UtrechtIconInEnOmUwHuis {
    }
    interface UtrechtIconInformatie {
    }
    interface UtrechtIconInformatieEnBetalen {
    }
    interface UtrechtIconInkomen {
    }
    interface UtrechtIconJeugd {
    }
    interface UtrechtIconKerstbomen {
    }
    interface UtrechtIconKindEnFamilie {
    }
    interface UtrechtIconKoningsdag {
    }
    interface UtrechtIconKopenEnHuren {
    }
    interface UtrechtIconKopenEnVerkopen {
    }
    interface UtrechtIconLeerlingenvervoer {
    }
    interface UtrechtIconLetOp {
    }
    interface UtrechtIconLiefdadigheid {
    }
    interface UtrechtIconLocatie {
    }
    interface UtrechtIconManege {
    }
    interface UtrechtIconMeeuwenoverlast {
    }
    interface UtrechtIconMelding {
    }
    interface UtrechtIconMeldingOpenbareRuimte {
    }
    interface UtrechtIconMobiliteit {
    }
    interface UtrechtIconMonitorAgrofood {
    }
    interface UtrechtIconMonitorDuurzaamheid {
    }
    interface UtrechtIconMonitorSociaal {
    }
    interface UtrechtIconMonitorVirus {
    }
    interface UtrechtIconMonitorWoningmarkt {
    }
    interface UtrechtIconNatuurLandschap {
    }
    interface UtrechtIconNieuwsbrief {
    }
    interface UtrechtIconOmgeving {
    }
    interface UtrechtIconOmgevingsvergunning {
    }
    interface UtrechtIconOnderhoud {
    }
    interface UtrechtIconOndernemen {
    }
    interface UtrechtIconOnderscheidingen {
    }
    interface UtrechtIconOnderwijs {
    }
    interface UtrechtIconOpeningstijden {
    }
    interface UtrechtIconOverDeGemeente {
    }
    interface UtrechtIconOverDeStad {
    }
    interface UtrechtIconParkeervoorzieningGehandicapten {
    }
    interface UtrechtIconParkeren {
    }
    interface UtrechtIconPaspoort {
    }
    interface UtrechtIconPaspoortIdkaartGecombineerd {
    }
    interface UtrechtIconPrijskaartje {
    }
    interface UtrechtIconRaadEnCollege {
    }
    interface UtrechtIconReclame {
    }
    interface UtrechtIconRecreatie {
    }
    interface UtrechtIconRegelingLaagInkomen {
    }
    interface UtrechtIconRijbewijs {
    }
    interface UtrechtIconSchoolkostenregeling {
    }
    interface UtrechtIconSinterklaas {
    }
    interface UtrechtIconSociaalZorgWelzijn {
    }
    interface UtrechtIconSport {
    }
    interface UtrechtIconSportCultureleActiviteit {
    }
    interface UtrechtIconSportkledingMuziekinstrumenten {
    }
    interface UtrechtIconStationSneltrein {
    }
    interface UtrechtIconStationStoptrein {
    }
    interface UtrechtIconStookverbod {
    }
    interface UtrechtIconStrand {
    }
    interface UtrechtIconSubsidie {
    }
    interface UtrechtIconTemperatuurMelding {
    }
    interface UtrechtIconTrouwenEnGeregistreerdPartnerschap {
    }
    interface UtrechtIconTuinbouw {
    }
    interface UtrechtIconUittreksel {
    }
    interface UtrechtIconUwGemeente {
    }
    interface UtrechtIconUwWijk {
    }
    interface UtrechtIconVacatures {
    }
    interface UtrechtIconVeerboot {
    }
    interface UtrechtIconVeiligeWijk {
    }
    interface UtrechtIconVergaderen {
    }
    interface UtrechtIconVergunningAlgemeen {
    }
    interface UtrechtIconVerhuizen {
    }
    interface UtrechtIconVerkiezingen {
    }
    interface UtrechtIconVervoersvoorziening {
    }
    interface UtrechtIconVirus {
    }
    interface UtrechtIconVluchtelingenOpvang {
    }
    interface UtrechtIconVoeding {
    }
    interface UtrechtIconVrijwilligerswerk {
    }
    interface UtrechtIconVuurwerk {
    }
    interface UtrechtIconWandelen {
    }
    interface UtrechtIconWerkzaamheden {
    }
    interface UtrechtIconWijkteam {
    }
    interface UtrechtIconWinkelen {
    }
    interface UtrechtIconWinkelwagen {
    }
    interface UtrechtIconWmo {
    }
    interface UtrechtIconWozWaarde {
    }
    interface UtrechtIconZwemabonnement {
    }
}
declare global {
    interface HTMLUtrechtIconActueelElement extends Components.UtrechtIconActueel, HTMLStencilElement {
    }
    var HTMLUtrechtIconActueelElement: {
        prototype: HTMLUtrechtIconActueelElement;
        new (): HTMLUtrechtIconActueelElement;
    };
    interface HTMLUtrechtIconAfvalElement extends Components.UtrechtIconAfval, HTMLStencilElement {
    }
    var HTMLUtrechtIconAfvalElement: {
        prototype: HTMLUtrechtIconAfvalElement;
        new (): HTMLUtrechtIconAfvalElement;
    };
    interface HTMLUtrechtIconAfvalContainerElement extends Components.UtrechtIconAfvalContainer, HTMLStencilElement {
    }
    var HTMLUtrechtIconAfvalContainerElement: {
        prototype: HTMLUtrechtIconAfvalContainerElement;
        new (): HTMLUtrechtIconAfvalContainerElement;
    };
    interface HTMLUtrechtIconAfvalOphaalElement extends Components.UtrechtIconAfvalOphaal, HTMLStencilElement {
    }
    var HTMLUtrechtIconAfvalOphaalElement: {
        prototype: HTMLUtrechtIconAfvalOphaalElement;
        new (): HTMLUtrechtIconAfvalOphaalElement;
    };
    interface HTMLUtrechtIconAfvalScheidenElement extends Components.UtrechtIconAfvalScheiden, HTMLStencilElement {
    }
    var HTMLUtrechtIconAfvalScheidenElement: {
        prototype: HTMLUtrechtIconAfvalScheidenElement;
        new (): HTMLUtrechtIconAfvalScheidenElement;
    };
    interface HTMLUtrechtIconAfvalkalenderElement extends Components.UtrechtIconAfvalkalender, HTMLStencilElement {
    }
    var HTMLUtrechtIconAfvalkalenderElement: {
        prototype: HTMLUtrechtIconAfvalkalenderElement;
        new (): HTMLUtrechtIconAfvalkalenderElement;
    };
    interface HTMLUtrechtIconAgendaElement extends Components.UtrechtIconAgenda, HTMLStencilElement {
    }
    var HTMLUtrechtIconAgendaElement: {
        prototype: HTMLUtrechtIconAgendaElement;
        new (): HTMLUtrechtIconAgendaElement;
    };
    interface HTMLUtrechtIconAirborneElement extends Components.UtrechtIconAirborne, HTMLStencilElement {
    }
    var HTMLUtrechtIconAirborneElement: {
        prototype: HTMLUtrechtIconAirborneElement;
        new (): HTMLUtrechtIconAirborneElement;
    };
    interface HTMLUtrechtIconAttentieElement extends Components.UtrechtIconAttentie, HTMLStencilElement {
    }
    var HTMLUtrechtIconAttentieElement: {
        prototype: HTMLUtrechtIconAttentieElement;
        new (): HTMLUtrechtIconAttentieElement;
    };
    interface HTMLUtrechtIconAutoElement extends Components.UtrechtIconAuto, HTMLStencilElement {
    }
    var HTMLUtrechtIconAutoElement: {
        prototype: HTMLUtrechtIconAutoElement;
        new (): HTMLUtrechtIconAutoElement;
    };
    interface HTMLUtrechtIconBedrijventerreinElement extends Components.UtrechtIconBedrijventerrein, HTMLStencilElement {
    }
    var HTMLUtrechtIconBedrijventerreinElement: {
        prototype: HTMLUtrechtIconBedrijventerreinElement;
        new (): HTMLUtrechtIconBedrijventerreinElement;
    };
    interface HTMLUtrechtIconBegrotingElement extends Components.UtrechtIconBegroting, HTMLStencilElement {
    }
    var HTMLUtrechtIconBegrotingElement: {
        prototype: HTMLUtrechtIconBegrotingElement;
        new (): HTMLUtrechtIconBegrotingElement;
    };
    interface HTMLUtrechtIconBelastingenElement extends Components.UtrechtIconBelastingen, HTMLStencilElement {
    }
    var HTMLUtrechtIconBelastingenElement: {
        prototype: HTMLUtrechtIconBelastingenElement;
        new (): HTMLUtrechtIconBelastingenElement;
    };
    interface HTMLUtrechtIconBevolkingElement extends Components.UtrechtIconBevolking, HTMLStencilElement {
    }
    var HTMLUtrechtIconBevolkingElement: {
        prototype: HTMLUtrechtIconBevolkingElement;
        new (): HTMLUtrechtIconBevolkingElement;
    };
    interface HTMLUtrechtIconBevrijdingElement extends Components.UtrechtIconBevrijding, HTMLStencilElement {
    }
    var HTMLUtrechtIconBevrijdingElement: {
        prototype: HTMLUtrechtIconBevrijdingElement;
        new (): HTMLUtrechtIconBevrijdingElement;
    };
    interface HTMLUtrechtIconBezwaarEnBeroepElement extends Components.UtrechtIconBezwaarEnBeroep, HTMLStencilElement {
    }
    var HTMLUtrechtIconBezwaarEnBeroepElement: {
        prototype: HTMLUtrechtIconBezwaarEnBeroepElement;
        new (): HTMLUtrechtIconBezwaarEnBeroepElement;
    };
    interface HTMLUtrechtIconBijstandsuitkeringElement extends Components.UtrechtIconBijstandsuitkering, HTMLStencilElement {
    }
    var HTMLUtrechtIconBijstandsuitkeringElement: {
        prototype: HTMLUtrechtIconBijstandsuitkeringElement;
        new (): HTMLUtrechtIconBijstandsuitkeringElement;
    };
    interface HTMLUtrechtIconBladerenOpruimenElement extends Components.UtrechtIconBladerenOpruimen, HTMLStencilElement {
    }
    var HTMLUtrechtIconBladerenOpruimenElement: {
        prototype: HTMLUtrechtIconBladerenOpruimenElement;
        new (): HTMLUtrechtIconBladerenOpruimenElement;
    };
    interface HTMLUtrechtIconBouwenEnVerbouwenElement extends Components.UtrechtIconBouwenEnVerbouwen, HTMLStencilElement {
    }
    var HTMLUtrechtIconBouwenEnVerbouwenElement: {
        prototype: HTMLUtrechtIconBouwenEnVerbouwenElement;
        new (): HTMLUtrechtIconBouwenEnVerbouwenElement;
    };
    interface HTMLUtrechtIconBrandgevaarElement extends Components.UtrechtIconBrandgevaar, HTMLStencilElement {
    }
    var HTMLUtrechtIconBrandgevaarElement: {
        prototype: HTMLUtrechtIconBrandgevaarElement;
        new (): HTMLUtrechtIconBrandgevaarElement;
    };
    interface HTMLUtrechtIconBuitengebiedElement extends Components.UtrechtIconBuitengebied, HTMLStencilElement {
    }
    var HTMLUtrechtIconBuitengebiedElement: {
        prototype: HTMLUtrechtIconBuitengebiedElement;
        new (): HTMLUtrechtIconBuitengebiedElement;
    };
    interface HTMLUtrechtIconComputerregelingElement extends Components.UtrechtIconComputerregeling, HTMLStencilElement {
    }
    var HTMLUtrechtIconComputerregelingElement: {
        prototype: HTMLUtrechtIconComputerregelingElement;
        new (): HTMLUtrechtIconComputerregelingElement;
    };
    interface HTMLUtrechtIconContactGemeenteElement extends Components.UtrechtIconContactGemeente, HTMLStencilElement {
    }
    var HTMLUtrechtIconContactGemeenteElement: {
        prototype: HTMLUtrechtIconContactGemeenteElement;
        new (): HTMLUtrechtIconContactGemeenteElement;
    };
    interface HTMLUtrechtIconContainerElement extends Components.UtrechtIconContainer, HTMLStencilElement {
    }
    var HTMLUtrechtIconContainerElement: {
        prototype: HTMLUtrechtIconContainerElement;
        new (): HTMLUtrechtIconContainerElement;
    };
    interface HTMLUtrechtIconDocumentenElement extends Components.UtrechtIconDocumenten, HTMLStencilElement {
    }
    var HTMLUtrechtIconDocumentenElement: {
        prototype: HTMLUtrechtIconDocumentenElement;
        new (): HTMLUtrechtIconDocumentenElement;
    };
    interface HTMLUtrechtIconDuurzaamheidElement extends Components.UtrechtIconDuurzaamheid, HTMLStencilElement {
    }
    var HTMLUtrechtIconDuurzaamheidElement: {
        prototype: HTMLUtrechtIconDuurzaamheidElement;
        new (): HTMLUtrechtIconDuurzaamheidElement;
    };
    interface HTMLUtrechtIconEconomieWerkInkomenElement extends Components.UtrechtIconEconomieWerkInkomen, HTMLStencilElement {
    }
    var HTMLUtrechtIconEconomieWerkInkomenElement: {
        prototype: HTMLUtrechtIconEconomieWerkInkomenElement;
        new (): HTMLUtrechtIconEconomieWerkInkomenElement;
    };
    interface HTMLUtrechtIconEikenprocessieElement extends Components.UtrechtIconEikenprocessie, HTMLStencilElement {
    }
    var HTMLUtrechtIconEikenprocessieElement: {
        prototype: HTMLUtrechtIconEikenprocessieElement;
        new (): HTMLUtrechtIconEikenprocessieElement;
    };
    interface HTMLUtrechtIconEnergietransitieElement extends Components.UtrechtIconEnergietransitie, HTMLStencilElement {
    }
    var HTMLUtrechtIconEnergietransitieElement: {
        prototype: HTMLUtrechtIconEnergietransitieElement;
        new (): HTMLUtrechtIconEnergietransitieElement;
    };
    interface HTMLUtrechtIconEvenementenElement extends Components.UtrechtIconEvenementen, HTMLStencilElement {
    }
    var HTMLUtrechtIconEvenementenElement: {
        prototype: HTMLUtrechtIconEvenementenElement;
        new (): HTMLUtrechtIconEvenementenElement;
    };
    interface HTMLUtrechtIconF1Element extends Components.UtrechtIconF1, HTMLStencilElement {
    }
    var HTMLUtrechtIconF1Element: {
        prototype: HTMLUtrechtIconF1Element;
        new (): HTMLUtrechtIconF1Element;
    };
    interface HTMLUtrechtIconFietsElement extends Components.UtrechtIconFiets, HTMLStencilElement {
    }
    var HTMLUtrechtIconFietsElement: {
        prototype: HTMLUtrechtIconFietsElement;
        new (): HTMLUtrechtIconFietsElement;
    };
    interface HTMLUtrechtIconGebruikerCentraalElement extends Components.UtrechtIconGebruikerCentraal, HTMLStencilElement {
    }
    var HTMLUtrechtIconGebruikerCentraalElement: {
        prototype: HTMLUtrechtIconGebruikerCentraalElement;
        new (): HTMLUtrechtIconGebruikerCentraalElement;
    };
    interface HTMLUtrechtIconGebruikerIngelogdElement extends Components.UtrechtIconGebruikerIngelogd, HTMLStencilElement {
    }
    var HTMLUtrechtIconGebruikerIngelogdElement: {
        prototype: HTMLUtrechtIconGebruikerIngelogdElement;
        new (): HTMLUtrechtIconGebruikerIngelogdElement;
    };
    interface HTMLUtrechtIconGebruikersvraagElement extends Components.UtrechtIconGebruikersvraag, HTMLStencilElement {
    }
    var HTMLUtrechtIconGebruikersvraagElement: {
        prototype: HTMLUtrechtIconGebruikersvraagElement;
        new (): HTMLUtrechtIconGebruikersvraagElement;
    };
    interface HTMLUtrechtIconGemeenteraadElement extends Components.UtrechtIconGemeenteraad, HTMLStencilElement {
    }
    var HTMLUtrechtIconGemeenteraadElement: {
        prototype: HTMLUtrechtIconGemeenteraadElement;
        new (): HTMLUtrechtIconGemeenteraadElement;
    };
    interface HTMLUtrechtIconGemivaLocatieElement extends Components.UtrechtIconGemivaLocatie, HTMLStencilElement {
    }
    var HTMLUtrechtIconGemivaLocatieElement: {
        prototype: HTMLUtrechtIconGemivaLocatieElement;
        new (): HTMLUtrechtIconGemivaLocatieElement;
    };
    interface HTMLUtrechtIconGezichtElement extends Components.UtrechtIconGezicht, HTMLStencilElement {
    }
    var HTMLUtrechtIconGezichtElement: {
        prototype: HTMLUtrechtIconGezichtElement;
        new (): HTMLUtrechtIconGezichtElement;
    };
    interface HTMLUtrechtIconGladheidElement extends Components.UtrechtIconGladheid, HTMLStencilElement {
    }
    var HTMLUtrechtIconGladheidElement: {
        prototype: HTMLUtrechtIconGladheidElement;
        new (): HTMLUtrechtIconGladheidElement;
    };
    interface HTMLUtrechtIconGrafiekElement extends Components.UtrechtIconGrafiek, HTMLStencilElement {
    }
    var HTMLUtrechtIconGrafiekElement: {
        prototype: HTMLUtrechtIconGrafiekElement;
        new (): HTMLUtrechtIconGrafiekElement;
    };
    interface HTMLUtrechtIconGrofvuilElement extends Components.UtrechtIconGrofvuil, HTMLStencilElement {
    }
    var HTMLUtrechtIconGrofvuilElement: {
        prototype: HTMLUtrechtIconGrofvuilElement;
        new (): HTMLUtrechtIconGrofvuilElement;
    };
    interface HTMLUtrechtIconHondenbelastingElement extends Components.UtrechtIconHondenbelasting, HTMLStencilElement {
    }
    var HTMLUtrechtIconHondenbelastingElement: {
        prototype: HTMLUtrechtIconHondenbelastingElement;
        new (): HTMLUtrechtIconHondenbelastingElement;
    };
    interface HTMLUtrechtIconHorecavergunningenElement extends Components.UtrechtIconHorecavergunningen, HTMLStencilElement {
    }
    var HTMLUtrechtIconHorecavergunningenElement: {
        prototype: HTMLUtrechtIconHorecavergunningenElement;
        new (): HTMLUtrechtIconHorecavergunningenElement;
    };
    interface HTMLUtrechtIconHuisElement extends Components.UtrechtIconHuis, HTMLStencilElement {
    }
    var HTMLUtrechtIconHuisElement: {
        prototype: HTMLUtrechtIconHuisElement;
        new (): HTMLUtrechtIconHuisElement;
    };
    interface HTMLUtrechtIconHuisEnOmgevingElement extends Components.UtrechtIconHuisEnOmgeving, HTMLStencilElement {
    }
    var HTMLUtrechtIconHuisEnOmgevingElement: {
        prototype: HTMLUtrechtIconHuisEnOmgevingElement;
        new (): HTMLUtrechtIconHuisEnOmgevingElement;
    };
    interface HTMLUtrechtIconHulpmiddelenVindenElement extends Components.UtrechtIconHulpmiddelenVinden, HTMLStencilElement {
    }
    var HTMLUtrechtIconHulpmiddelenVindenElement: {
        prototype: HTMLUtrechtIconHulpmiddelenVindenElement;
        new (): HTMLUtrechtIconHulpmiddelenVindenElement;
    };
    interface HTMLUtrechtIconIdkaartElement extends Components.UtrechtIconIdkaart, HTMLStencilElement {
    }
    var HTMLUtrechtIconIdkaartElement: {
        prototype: HTMLUtrechtIconIdkaartElement;
        new (): HTMLUtrechtIconIdkaartElement;
    };
    interface HTMLUtrechtIconInEnOmUwHuisElement extends Components.UtrechtIconInEnOmUwHuis, HTMLStencilElement {
    }
    var HTMLUtrechtIconInEnOmUwHuisElement: {
        prototype: HTMLUtrechtIconInEnOmUwHuisElement;
        new (): HTMLUtrechtIconInEnOmUwHuisElement;
    };
    interface HTMLUtrechtIconInformatieElement extends Components.UtrechtIconInformatie, HTMLStencilElement {
    }
    var HTMLUtrechtIconInformatieElement: {
        prototype: HTMLUtrechtIconInformatieElement;
        new (): HTMLUtrechtIconInformatieElement;
    };
    interface HTMLUtrechtIconInformatieEnBetalenElement extends Components.UtrechtIconInformatieEnBetalen, HTMLStencilElement {
    }
    var HTMLUtrechtIconInformatieEnBetalenElement: {
        prototype: HTMLUtrechtIconInformatieEnBetalenElement;
        new (): HTMLUtrechtIconInformatieEnBetalenElement;
    };
    interface HTMLUtrechtIconInkomenElement extends Components.UtrechtIconInkomen, HTMLStencilElement {
    }
    var HTMLUtrechtIconInkomenElement: {
        prototype: HTMLUtrechtIconInkomenElement;
        new (): HTMLUtrechtIconInkomenElement;
    };
    interface HTMLUtrechtIconJeugdElement extends Components.UtrechtIconJeugd, HTMLStencilElement {
    }
    var HTMLUtrechtIconJeugdElement: {
        prototype: HTMLUtrechtIconJeugdElement;
        new (): HTMLUtrechtIconJeugdElement;
    };
    interface HTMLUtrechtIconKerstbomenElement extends Components.UtrechtIconKerstbomen, HTMLStencilElement {
    }
    var HTMLUtrechtIconKerstbomenElement: {
        prototype: HTMLUtrechtIconKerstbomenElement;
        new (): HTMLUtrechtIconKerstbomenElement;
    };
    interface HTMLUtrechtIconKindEnFamilieElement extends Components.UtrechtIconKindEnFamilie, HTMLStencilElement {
    }
    var HTMLUtrechtIconKindEnFamilieElement: {
        prototype: HTMLUtrechtIconKindEnFamilieElement;
        new (): HTMLUtrechtIconKindEnFamilieElement;
    };
    interface HTMLUtrechtIconKoningsdagElement extends Components.UtrechtIconKoningsdag, HTMLStencilElement {
    }
    var HTMLUtrechtIconKoningsdagElement: {
        prototype: HTMLUtrechtIconKoningsdagElement;
        new (): HTMLUtrechtIconKoningsdagElement;
    };
    interface HTMLUtrechtIconKopenEnHurenElement extends Components.UtrechtIconKopenEnHuren, HTMLStencilElement {
    }
    var HTMLUtrechtIconKopenEnHurenElement: {
        prototype: HTMLUtrechtIconKopenEnHurenElement;
        new (): HTMLUtrechtIconKopenEnHurenElement;
    };
    interface HTMLUtrechtIconKopenEnVerkopenElement extends Components.UtrechtIconKopenEnVerkopen, HTMLStencilElement {
    }
    var HTMLUtrechtIconKopenEnVerkopenElement: {
        prototype: HTMLUtrechtIconKopenEnVerkopenElement;
        new (): HTMLUtrechtIconKopenEnVerkopenElement;
    };
    interface HTMLUtrechtIconLeerlingenvervoerElement extends Components.UtrechtIconLeerlingenvervoer, HTMLStencilElement {
    }
    var HTMLUtrechtIconLeerlingenvervoerElement: {
        prototype: HTMLUtrechtIconLeerlingenvervoerElement;
        new (): HTMLUtrechtIconLeerlingenvervoerElement;
    };
    interface HTMLUtrechtIconLetOpElement extends Components.UtrechtIconLetOp, HTMLStencilElement {
    }
    var HTMLUtrechtIconLetOpElement: {
        prototype: HTMLUtrechtIconLetOpElement;
        new (): HTMLUtrechtIconLetOpElement;
    };
    interface HTMLUtrechtIconLiefdadigheidElement extends Components.UtrechtIconLiefdadigheid, HTMLStencilElement {
    }
    var HTMLUtrechtIconLiefdadigheidElement: {
        prototype: HTMLUtrechtIconLiefdadigheidElement;
        new (): HTMLUtrechtIconLiefdadigheidElement;
    };
    interface HTMLUtrechtIconLocatieElement extends Components.UtrechtIconLocatie, HTMLStencilElement {
    }
    var HTMLUtrechtIconLocatieElement: {
        prototype: HTMLUtrechtIconLocatieElement;
        new (): HTMLUtrechtIconLocatieElement;
    };
    interface HTMLUtrechtIconManegeElement extends Components.UtrechtIconManege, HTMLStencilElement {
    }
    var HTMLUtrechtIconManegeElement: {
        prototype: HTMLUtrechtIconManegeElement;
        new (): HTMLUtrechtIconManegeElement;
    };
    interface HTMLUtrechtIconMeeuwenoverlastElement extends Components.UtrechtIconMeeuwenoverlast, HTMLStencilElement {
    }
    var HTMLUtrechtIconMeeuwenoverlastElement: {
        prototype: HTMLUtrechtIconMeeuwenoverlastElement;
        new (): HTMLUtrechtIconMeeuwenoverlastElement;
    };
    interface HTMLUtrechtIconMeldingElement extends Components.UtrechtIconMelding, HTMLStencilElement {
    }
    var HTMLUtrechtIconMeldingElement: {
        prototype: HTMLUtrechtIconMeldingElement;
        new (): HTMLUtrechtIconMeldingElement;
    };
    interface HTMLUtrechtIconMeldingOpenbareRuimteElement extends Components.UtrechtIconMeldingOpenbareRuimte, HTMLStencilElement {
    }
    var HTMLUtrechtIconMeldingOpenbareRuimteElement: {
        prototype: HTMLUtrechtIconMeldingOpenbareRuimteElement;
        new (): HTMLUtrechtIconMeldingOpenbareRuimteElement;
    };
    interface HTMLUtrechtIconMobiliteitElement extends Components.UtrechtIconMobiliteit, HTMLStencilElement {
    }
    var HTMLUtrechtIconMobiliteitElement: {
        prototype: HTMLUtrechtIconMobiliteitElement;
        new (): HTMLUtrechtIconMobiliteitElement;
    };
    interface HTMLUtrechtIconMonitorAgrofoodElement extends Components.UtrechtIconMonitorAgrofood, HTMLStencilElement {
    }
    var HTMLUtrechtIconMonitorAgrofoodElement: {
        prototype: HTMLUtrechtIconMonitorAgrofoodElement;
        new (): HTMLUtrechtIconMonitorAgrofoodElement;
    };
    interface HTMLUtrechtIconMonitorDuurzaamheidElement extends Components.UtrechtIconMonitorDuurzaamheid, HTMLStencilElement {
    }
    var HTMLUtrechtIconMonitorDuurzaamheidElement: {
        prototype: HTMLUtrechtIconMonitorDuurzaamheidElement;
        new (): HTMLUtrechtIconMonitorDuurzaamheidElement;
    };
    interface HTMLUtrechtIconMonitorSociaalElement extends Components.UtrechtIconMonitorSociaal, HTMLStencilElement {
    }
    var HTMLUtrechtIconMonitorSociaalElement: {
        prototype: HTMLUtrechtIconMonitorSociaalElement;
        new (): HTMLUtrechtIconMonitorSociaalElement;
    };
    interface HTMLUtrechtIconMonitorVirusElement extends Components.UtrechtIconMonitorVirus, HTMLStencilElement {
    }
    var HTMLUtrechtIconMonitorVirusElement: {
        prototype: HTMLUtrechtIconMonitorVirusElement;
        new (): HTMLUtrechtIconMonitorVirusElement;
    };
    interface HTMLUtrechtIconMonitorWoningmarktElement extends Components.UtrechtIconMonitorWoningmarkt, HTMLStencilElement {
    }
    var HTMLUtrechtIconMonitorWoningmarktElement: {
        prototype: HTMLUtrechtIconMonitorWoningmarktElement;
        new (): HTMLUtrechtIconMonitorWoningmarktElement;
    };
    interface HTMLUtrechtIconNatuurLandschapElement extends Components.UtrechtIconNatuurLandschap, HTMLStencilElement {
    }
    var HTMLUtrechtIconNatuurLandschapElement: {
        prototype: HTMLUtrechtIconNatuurLandschapElement;
        new (): HTMLUtrechtIconNatuurLandschapElement;
    };
    interface HTMLUtrechtIconNieuwsbriefElement extends Components.UtrechtIconNieuwsbrief, HTMLStencilElement {
    }
    var HTMLUtrechtIconNieuwsbriefElement: {
        prototype: HTMLUtrechtIconNieuwsbriefElement;
        new (): HTMLUtrechtIconNieuwsbriefElement;
    };
    interface HTMLUtrechtIconOmgevingElement extends Components.UtrechtIconOmgeving, HTMLStencilElement {
    }
    var HTMLUtrechtIconOmgevingElement: {
        prototype: HTMLUtrechtIconOmgevingElement;
        new (): HTMLUtrechtIconOmgevingElement;
    };
    interface HTMLUtrechtIconOmgevingsvergunningElement extends Components.UtrechtIconOmgevingsvergunning, HTMLStencilElement {
    }
    var HTMLUtrechtIconOmgevingsvergunningElement: {
        prototype: HTMLUtrechtIconOmgevingsvergunningElement;
        new (): HTMLUtrechtIconOmgevingsvergunningElement;
    };
    interface HTMLUtrechtIconOnderhoudElement extends Components.UtrechtIconOnderhoud, HTMLStencilElement {
    }
    var HTMLUtrechtIconOnderhoudElement: {
        prototype: HTMLUtrechtIconOnderhoudElement;
        new (): HTMLUtrechtIconOnderhoudElement;
    };
    interface HTMLUtrechtIconOndernemenElement extends Components.UtrechtIconOndernemen, HTMLStencilElement {
    }
    var HTMLUtrechtIconOndernemenElement: {
        prototype: HTMLUtrechtIconOndernemenElement;
        new (): HTMLUtrechtIconOndernemenElement;
    };
    interface HTMLUtrechtIconOnderscheidingenElement extends Components.UtrechtIconOnderscheidingen, HTMLStencilElement {
    }
    var HTMLUtrechtIconOnderscheidingenElement: {
        prototype: HTMLUtrechtIconOnderscheidingenElement;
        new (): HTMLUtrechtIconOnderscheidingenElement;
    };
    interface HTMLUtrechtIconOnderwijsElement extends Components.UtrechtIconOnderwijs, HTMLStencilElement {
    }
    var HTMLUtrechtIconOnderwijsElement: {
        prototype: HTMLUtrechtIconOnderwijsElement;
        new (): HTMLUtrechtIconOnderwijsElement;
    };
    interface HTMLUtrechtIconOpeningstijdenElement extends Components.UtrechtIconOpeningstijden, HTMLStencilElement {
    }
    var HTMLUtrechtIconOpeningstijdenElement: {
        prototype: HTMLUtrechtIconOpeningstijdenElement;
        new (): HTMLUtrechtIconOpeningstijdenElement;
    };
    interface HTMLUtrechtIconOverDeGemeenteElement extends Components.UtrechtIconOverDeGemeente, HTMLStencilElement {
    }
    var HTMLUtrechtIconOverDeGemeenteElement: {
        prototype: HTMLUtrechtIconOverDeGemeenteElement;
        new (): HTMLUtrechtIconOverDeGemeenteElement;
    };
    interface HTMLUtrechtIconOverDeStadElement extends Components.UtrechtIconOverDeStad, HTMLStencilElement {
    }
    var HTMLUtrechtIconOverDeStadElement: {
        prototype: HTMLUtrechtIconOverDeStadElement;
        new (): HTMLUtrechtIconOverDeStadElement;
    };
    interface HTMLUtrechtIconParkeervoorzieningGehandicaptenElement extends Components.UtrechtIconParkeervoorzieningGehandicapten, HTMLStencilElement {
    }
    var HTMLUtrechtIconParkeervoorzieningGehandicaptenElement: {
        prototype: HTMLUtrechtIconParkeervoorzieningGehandicaptenElement;
        new (): HTMLUtrechtIconParkeervoorzieningGehandicaptenElement;
    };
    interface HTMLUtrechtIconParkerenElement extends Components.UtrechtIconParkeren, HTMLStencilElement {
    }
    var HTMLUtrechtIconParkerenElement: {
        prototype: HTMLUtrechtIconParkerenElement;
        new (): HTMLUtrechtIconParkerenElement;
    };
    interface HTMLUtrechtIconPaspoortElement extends Components.UtrechtIconPaspoort, HTMLStencilElement {
    }
    var HTMLUtrechtIconPaspoortElement: {
        prototype: HTMLUtrechtIconPaspoortElement;
        new (): HTMLUtrechtIconPaspoortElement;
    };
    interface HTMLUtrechtIconPaspoortIdkaartGecombineerdElement extends Components.UtrechtIconPaspoortIdkaartGecombineerd, HTMLStencilElement {
    }
    var HTMLUtrechtIconPaspoortIdkaartGecombineerdElement: {
        prototype: HTMLUtrechtIconPaspoortIdkaartGecombineerdElement;
        new (): HTMLUtrechtIconPaspoortIdkaartGecombineerdElement;
    };
    interface HTMLUtrechtIconPrijskaartjeElement extends Components.UtrechtIconPrijskaartje, HTMLStencilElement {
    }
    var HTMLUtrechtIconPrijskaartjeElement: {
        prototype: HTMLUtrechtIconPrijskaartjeElement;
        new (): HTMLUtrechtIconPrijskaartjeElement;
    };
    interface HTMLUtrechtIconRaadEnCollegeElement extends Components.UtrechtIconRaadEnCollege, HTMLStencilElement {
    }
    var HTMLUtrechtIconRaadEnCollegeElement: {
        prototype: HTMLUtrechtIconRaadEnCollegeElement;
        new (): HTMLUtrechtIconRaadEnCollegeElement;
    };
    interface HTMLUtrechtIconReclameElement extends Components.UtrechtIconReclame, HTMLStencilElement {
    }
    var HTMLUtrechtIconReclameElement: {
        prototype: HTMLUtrechtIconReclameElement;
        new (): HTMLUtrechtIconReclameElement;
    };
    interface HTMLUtrechtIconRecreatieElement extends Components.UtrechtIconRecreatie, HTMLStencilElement {
    }
    var HTMLUtrechtIconRecreatieElement: {
        prototype: HTMLUtrechtIconRecreatieElement;
        new (): HTMLUtrechtIconRecreatieElement;
    };
    interface HTMLUtrechtIconRegelingLaagInkomenElement extends Components.UtrechtIconRegelingLaagInkomen, HTMLStencilElement {
    }
    var HTMLUtrechtIconRegelingLaagInkomenElement: {
        prototype: HTMLUtrechtIconRegelingLaagInkomenElement;
        new (): HTMLUtrechtIconRegelingLaagInkomenElement;
    };
    interface HTMLUtrechtIconRijbewijsElement extends Components.UtrechtIconRijbewijs, HTMLStencilElement {
    }
    var HTMLUtrechtIconRijbewijsElement: {
        prototype: HTMLUtrechtIconRijbewijsElement;
        new (): HTMLUtrechtIconRijbewijsElement;
    };
    interface HTMLUtrechtIconSchoolkostenregelingElement extends Components.UtrechtIconSchoolkostenregeling, HTMLStencilElement {
    }
    var HTMLUtrechtIconSchoolkostenregelingElement: {
        prototype: HTMLUtrechtIconSchoolkostenregelingElement;
        new (): HTMLUtrechtIconSchoolkostenregelingElement;
    };
    interface HTMLUtrechtIconSinterklaasElement extends Components.UtrechtIconSinterklaas, HTMLStencilElement {
    }
    var HTMLUtrechtIconSinterklaasElement: {
        prototype: HTMLUtrechtIconSinterklaasElement;
        new (): HTMLUtrechtIconSinterklaasElement;
    };
    interface HTMLUtrechtIconSociaalZorgWelzijnElement extends Components.UtrechtIconSociaalZorgWelzijn, HTMLStencilElement {
    }
    var HTMLUtrechtIconSociaalZorgWelzijnElement: {
        prototype: HTMLUtrechtIconSociaalZorgWelzijnElement;
        new (): HTMLUtrechtIconSociaalZorgWelzijnElement;
    };
    interface HTMLUtrechtIconSportElement extends Components.UtrechtIconSport, HTMLStencilElement {
    }
    var HTMLUtrechtIconSportElement: {
        prototype: HTMLUtrechtIconSportElement;
        new (): HTMLUtrechtIconSportElement;
    };
    interface HTMLUtrechtIconSportCultureleActiviteitElement extends Components.UtrechtIconSportCultureleActiviteit, HTMLStencilElement {
    }
    var HTMLUtrechtIconSportCultureleActiviteitElement: {
        prototype: HTMLUtrechtIconSportCultureleActiviteitElement;
        new (): HTMLUtrechtIconSportCultureleActiviteitElement;
    };
    interface HTMLUtrechtIconSportkledingMuziekinstrumentenElement extends Components.UtrechtIconSportkledingMuziekinstrumenten, HTMLStencilElement {
    }
    var HTMLUtrechtIconSportkledingMuziekinstrumentenElement: {
        prototype: HTMLUtrechtIconSportkledingMuziekinstrumentenElement;
        new (): HTMLUtrechtIconSportkledingMuziekinstrumentenElement;
    };
    interface HTMLUtrechtIconStationSneltreinElement extends Components.UtrechtIconStationSneltrein, HTMLStencilElement {
    }
    var HTMLUtrechtIconStationSneltreinElement: {
        prototype: HTMLUtrechtIconStationSneltreinElement;
        new (): HTMLUtrechtIconStationSneltreinElement;
    };
    interface HTMLUtrechtIconStationStoptreinElement extends Components.UtrechtIconStationStoptrein, HTMLStencilElement {
    }
    var HTMLUtrechtIconStationStoptreinElement: {
        prototype: HTMLUtrechtIconStationStoptreinElement;
        new (): HTMLUtrechtIconStationStoptreinElement;
    };
    interface HTMLUtrechtIconStookverbodElement extends Components.UtrechtIconStookverbod, HTMLStencilElement {
    }
    var HTMLUtrechtIconStookverbodElement: {
        prototype: HTMLUtrechtIconStookverbodElement;
        new (): HTMLUtrechtIconStookverbodElement;
    };
    interface HTMLUtrechtIconStrandElement extends Components.UtrechtIconStrand, HTMLStencilElement {
    }
    var HTMLUtrechtIconStrandElement: {
        prototype: HTMLUtrechtIconStrandElement;
        new (): HTMLUtrechtIconStrandElement;
    };
    interface HTMLUtrechtIconSubsidieElement extends Components.UtrechtIconSubsidie, HTMLStencilElement {
    }
    var HTMLUtrechtIconSubsidieElement: {
        prototype: HTMLUtrechtIconSubsidieElement;
        new (): HTMLUtrechtIconSubsidieElement;
    };
    interface HTMLUtrechtIconTemperatuurMeldingElement extends Components.UtrechtIconTemperatuurMelding, HTMLStencilElement {
    }
    var HTMLUtrechtIconTemperatuurMeldingElement: {
        prototype: HTMLUtrechtIconTemperatuurMeldingElement;
        new (): HTMLUtrechtIconTemperatuurMeldingElement;
    };
    interface HTMLUtrechtIconTrouwenEnGeregistreerdPartnerschapElement extends Components.UtrechtIconTrouwenEnGeregistreerdPartnerschap, HTMLStencilElement {
    }
    var HTMLUtrechtIconTrouwenEnGeregistreerdPartnerschapElement: {
        prototype: HTMLUtrechtIconTrouwenEnGeregistreerdPartnerschapElement;
        new (): HTMLUtrechtIconTrouwenEnGeregistreerdPartnerschapElement;
    };
    interface HTMLUtrechtIconTuinbouwElement extends Components.UtrechtIconTuinbouw, HTMLStencilElement {
    }
    var HTMLUtrechtIconTuinbouwElement: {
        prototype: HTMLUtrechtIconTuinbouwElement;
        new (): HTMLUtrechtIconTuinbouwElement;
    };
    interface HTMLUtrechtIconUittrekselElement extends Components.UtrechtIconUittreksel, HTMLStencilElement {
    }
    var HTMLUtrechtIconUittrekselElement: {
        prototype: HTMLUtrechtIconUittrekselElement;
        new (): HTMLUtrechtIconUittrekselElement;
    };
    interface HTMLUtrechtIconUwGemeenteElement extends Components.UtrechtIconUwGemeente, HTMLStencilElement {
    }
    var HTMLUtrechtIconUwGemeenteElement: {
        prototype: HTMLUtrechtIconUwGemeenteElement;
        new (): HTMLUtrechtIconUwGemeenteElement;
    };
    interface HTMLUtrechtIconUwWijkElement extends Components.UtrechtIconUwWijk, HTMLStencilElement {
    }
    var HTMLUtrechtIconUwWijkElement: {
        prototype: HTMLUtrechtIconUwWijkElement;
        new (): HTMLUtrechtIconUwWijkElement;
    };
    interface HTMLUtrechtIconVacaturesElement extends Components.UtrechtIconVacatures, HTMLStencilElement {
    }
    var HTMLUtrechtIconVacaturesElement: {
        prototype: HTMLUtrechtIconVacaturesElement;
        new (): HTMLUtrechtIconVacaturesElement;
    };
    interface HTMLUtrechtIconVeerbootElement extends Components.UtrechtIconVeerboot, HTMLStencilElement {
    }
    var HTMLUtrechtIconVeerbootElement: {
        prototype: HTMLUtrechtIconVeerbootElement;
        new (): HTMLUtrechtIconVeerbootElement;
    };
    interface HTMLUtrechtIconVeiligeWijkElement extends Components.UtrechtIconVeiligeWijk, HTMLStencilElement {
    }
    var HTMLUtrechtIconVeiligeWijkElement: {
        prototype: HTMLUtrechtIconVeiligeWijkElement;
        new (): HTMLUtrechtIconVeiligeWijkElement;
    };
    interface HTMLUtrechtIconVergaderenElement extends Components.UtrechtIconVergaderen, HTMLStencilElement {
    }
    var HTMLUtrechtIconVergaderenElement: {
        prototype: HTMLUtrechtIconVergaderenElement;
        new (): HTMLUtrechtIconVergaderenElement;
    };
    interface HTMLUtrechtIconVergunningAlgemeenElement extends Components.UtrechtIconVergunningAlgemeen, HTMLStencilElement {
    }
    var HTMLUtrechtIconVergunningAlgemeenElement: {
        prototype: HTMLUtrechtIconVergunningAlgemeenElement;
        new (): HTMLUtrechtIconVergunningAlgemeenElement;
    };
    interface HTMLUtrechtIconVerhuizenElement extends Components.UtrechtIconVerhuizen, HTMLStencilElement {
    }
    var HTMLUtrechtIconVerhuizenElement: {
        prototype: HTMLUtrechtIconVerhuizenElement;
        new (): HTMLUtrechtIconVerhuizenElement;
    };
    interface HTMLUtrechtIconVerkiezingenElement extends Components.UtrechtIconVerkiezingen, HTMLStencilElement {
    }
    var HTMLUtrechtIconVerkiezingenElement: {
        prototype: HTMLUtrechtIconVerkiezingenElement;
        new (): HTMLUtrechtIconVerkiezingenElement;
    };
    interface HTMLUtrechtIconVervoersvoorzieningElement extends Components.UtrechtIconVervoersvoorziening, HTMLStencilElement {
    }
    var HTMLUtrechtIconVervoersvoorzieningElement: {
        prototype: HTMLUtrechtIconVervoersvoorzieningElement;
        new (): HTMLUtrechtIconVervoersvoorzieningElement;
    };
    interface HTMLUtrechtIconVirusElement extends Components.UtrechtIconVirus, HTMLStencilElement {
    }
    var HTMLUtrechtIconVirusElement: {
        prototype: HTMLUtrechtIconVirusElement;
        new (): HTMLUtrechtIconVirusElement;
    };
    interface HTMLUtrechtIconVluchtelingenOpvangElement extends Components.UtrechtIconVluchtelingenOpvang, HTMLStencilElement {
    }
    var HTMLUtrechtIconVluchtelingenOpvangElement: {
        prototype: HTMLUtrechtIconVluchtelingenOpvangElement;
        new (): HTMLUtrechtIconVluchtelingenOpvangElement;
    };
    interface HTMLUtrechtIconVoedingElement extends Components.UtrechtIconVoeding, HTMLStencilElement {
    }
    var HTMLUtrechtIconVoedingElement: {
        prototype: HTMLUtrechtIconVoedingElement;
        new (): HTMLUtrechtIconVoedingElement;
    };
    interface HTMLUtrechtIconVrijwilligerswerkElement extends Components.UtrechtIconVrijwilligerswerk, HTMLStencilElement {
    }
    var HTMLUtrechtIconVrijwilligerswerkElement: {
        prototype: HTMLUtrechtIconVrijwilligerswerkElement;
        new (): HTMLUtrechtIconVrijwilligerswerkElement;
    };
    interface HTMLUtrechtIconVuurwerkElement extends Components.UtrechtIconVuurwerk, HTMLStencilElement {
    }
    var HTMLUtrechtIconVuurwerkElement: {
        prototype: HTMLUtrechtIconVuurwerkElement;
        new (): HTMLUtrechtIconVuurwerkElement;
    };
    interface HTMLUtrechtIconWandelenElement extends Components.UtrechtIconWandelen, HTMLStencilElement {
    }
    var HTMLUtrechtIconWandelenElement: {
        prototype: HTMLUtrechtIconWandelenElement;
        new (): HTMLUtrechtIconWandelenElement;
    };
    interface HTMLUtrechtIconWerkzaamhedenElement extends Components.UtrechtIconWerkzaamheden, HTMLStencilElement {
    }
    var HTMLUtrechtIconWerkzaamhedenElement: {
        prototype: HTMLUtrechtIconWerkzaamhedenElement;
        new (): HTMLUtrechtIconWerkzaamhedenElement;
    };
    interface HTMLUtrechtIconWijkteamElement extends Components.UtrechtIconWijkteam, HTMLStencilElement {
    }
    var HTMLUtrechtIconWijkteamElement: {
        prototype: HTMLUtrechtIconWijkteamElement;
        new (): HTMLUtrechtIconWijkteamElement;
    };
    interface HTMLUtrechtIconWinkelenElement extends Components.UtrechtIconWinkelen, HTMLStencilElement {
    }
    var HTMLUtrechtIconWinkelenElement: {
        prototype: HTMLUtrechtIconWinkelenElement;
        new (): HTMLUtrechtIconWinkelenElement;
    };
    interface HTMLUtrechtIconWinkelwagenElement extends Components.UtrechtIconWinkelwagen, HTMLStencilElement {
    }
    var HTMLUtrechtIconWinkelwagenElement: {
        prototype: HTMLUtrechtIconWinkelwagenElement;
        new (): HTMLUtrechtIconWinkelwagenElement;
    };
    interface HTMLUtrechtIconWmoElement extends Components.UtrechtIconWmo, HTMLStencilElement {
    }
    var HTMLUtrechtIconWmoElement: {
        prototype: HTMLUtrechtIconWmoElement;
        new (): HTMLUtrechtIconWmoElement;
    };
    interface HTMLUtrechtIconWozWaardeElement extends Components.UtrechtIconWozWaarde, HTMLStencilElement {
    }
    var HTMLUtrechtIconWozWaardeElement: {
        prototype: HTMLUtrechtIconWozWaardeElement;
        new (): HTMLUtrechtIconWozWaardeElement;
    };
    interface HTMLUtrechtIconZwemabonnementElement extends Components.UtrechtIconZwemabonnement, HTMLStencilElement {
    }
    var HTMLUtrechtIconZwemabonnementElement: {
        prototype: HTMLUtrechtIconZwemabonnementElement;
        new (): HTMLUtrechtIconZwemabonnementElement;
    };
    interface HTMLElementTagNameMap {
        "utrecht-icon-actueel": HTMLUtrechtIconActueelElement;
        "utrecht-icon-afval": HTMLUtrechtIconAfvalElement;
        "utrecht-icon-afval-container": HTMLUtrechtIconAfvalContainerElement;
        "utrecht-icon-afval-ophaal": HTMLUtrechtIconAfvalOphaalElement;
        "utrecht-icon-afval-scheiden": HTMLUtrechtIconAfvalScheidenElement;
        "utrecht-icon-afvalkalender": HTMLUtrechtIconAfvalkalenderElement;
        "utrecht-icon-agenda": HTMLUtrechtIconAgendaElement;
        "utrecht-icon-airborne": HTMLUtrechtIconAirborneElement;
        "utrecht-icon-attentie": HTMLUtrechtIconAttentieElement;
        "utrecht-icon-auto": HTMLUtrechtIconAutoElement;
        "utrecht-icon-bedrijventerrein": HTMLUtrechtIconBedrijventerreinElement;
        "utrecht-icon-begroting": HTMLUtrechtIconBegrotingElement;
        "utrecht-icon-belastingen": HTMLUtrechtIconBelastingenElement;
        "utrecht-icon-bevolking": HTMLUtrechtIconBevolkingElement;
        "utrecht-icon-bevrijding": HTMLUtrechtIconBevrijdingElement;
        "utrecht-icon-bezwaar-en-beroep": HTMLUtrechtIconBezwaarEnBeroepElement;
        "utrecht-icon-bijstandsuitkering": HTMLUtrechtIconBijstandsuitkeringElement;
        "utrecht-icon-bladeren-opruimen": HTMLUtrechtIconBladerenOpruimenElement;
        "utrecht-icon-bouwen-en-verbouwen": HTMLUtrechtIconBouwenEnVerbouwenElement;
        "utrecht-icon-brandgevaar": HTMLUtrechtIconBrandgevaarElement;
        "utrecht-icon-buitengebied": HTMLUtrechtIconBuitengebiedElement;
        "utrecht-icon-computerregeling": HTMLUtrechtIconComputerregelingElement;
        "utrecht-icon-contact-gemeente": HTMLUtrechtIconContactGemeenteElement;
        "utrecht-icon-container": HTMLUtrechtIconContainerElement;
        "utrecht-icon-documenten": HTMLUtrechtIconDocumentenElement;
        "utrecht-icon-duurzaamheid": HTMLUtrechtIconDuurzaamheidElement;
        "utrecht-icon-economie-werk-inkomen": HTMLUtrechtIconEconomieWerkInkomenElement;
        "utrecht-icon-eikenprocessie": HTMLUtrechtIconEikenprocessieElement;
        "utrecht-icon-energietransitie": HTMLUtrechtIconEnergietransitieElement;
        "utrecht-icon-evenementen": HTMLUtrechtIconEvenementenElement;
        "utrecht-icon-f-1": HTMLUtrechtIconF1Element;
        "utrecht-icon-fiets": HTMLUtrechtIconFietsElement;
        "utrecht-icon-gebruiker-centraal": HTMLUtrechtIconGebruikerCentraalElement;
        "utrecht-icon-gebruiker-ingelogd": HTMLUtrechtIconGebruikerIngelogdElement;
        "utrecht-icon-gebruikersvraag": HTMLUtrechtIconGebruikersvraagElement;
        "utrecht-icon-gemeenteraad": HTMLUtrechtIconGemeenteraadElement;
        "utrecht-icon-gemiva-locatie": HTMLUtrechtIconGemivaLocatieElement;
        "utrecht-icon-gezicht": HTMLUtrechtIconGezichtElement;
        "utrecht-icon-gladheid": HTMLUtrechtIconGladheidElement;
        "utrecht-icon-grafiek": HTMLUtrechtIconGrafiekElement;
        "utrecht-icon-grofvuil": HTMLUtrechtIconGrofvuilElement;
        "utrecht-icon-hondenbelasting": HTMLUtrechtIconHondenbelastingElement;
        "utrecht-icon-horecavergunningen": HTMLUtrechtIconHorecavergunningenElement;
        "utrecht-icon-huis": HTMLUtrechtIconHuisElement;
        "utrecht-icon-huis-en-omgeving": HTMLUtrechtIconHuisEnOmgevingElement;
        "utrecht-icon-hulpmiddelen-vinden": HTMLUtrechtIconHulpmiddelenVindenElement;
        "utrecht-icon-idkaart": HTMLUtrechtIconIdkaartElement;
        "utrecht-icon-in-en-om-uw-huis": HTMLUtrechtIconInEnOmUwHuisElement;
        "utrecht-icon-informatie": HTMLUtrechtIconInformatieElement;
        "utrecht-icon-informatie-en-betalen": HTMLUtrechtIconInformatieEnBetalenElement;
        "utrecht-icon-inkomen": HTMLUtrechtIconInkomenElement;
        "utrecht-icon-jeugd": HTMLUtrechtIconJeugdElement;
        "utrecht-icon-kerstbomen": HTMLUtrechtIconKerstbomenElement;
        "utrecht-icon-kind-en-familie": HTMLUtrechtIconKindEnFamilieElement;
        "utrecht-icon-koningsdag": HTMLUtrechtIconKoningsdagElement;
        "utrecht-icon-kopen-en-huren": HTMLUtrechtIconKopenEnHurenElement;
        "utrecht-icon-kopen-en-verkopen": HTMLUtrechtIconKopenEnVerkopenElement;
        "utrecht-icon-leerlingenvervoer": HTMLUtrechtIconLeerlingenvervoerElement;
        "utrecht-icon-let-op": HTMLUtrechtIconLetOpElement;
        "utrecht-icon-liefdadigheid": HTMLUtrechtIconLiefdadigheidElement;
        "utrecht-icon-locatie": HTMLUtrechtIconLocatieElement;
        "utrecht-icon-manege": HTMLUtrechtIconManegeElement;
        "utrecht-icon-meeuwenoverlast": HTMLUtrechtIconMeeuwenoverlastElement;
        "utrecht-icon-melding": HTMLUtrechtIconMeldingElement;
        "utrecht-icon-melding-openbare-ruimte": HTMLUtrechtIconMeldingOpenbareRuimteElement;
        "utrecht-icon-mobiliteit": HTMLUtrechtIconMobiliteitElement;
        "utrecht-icon-monitor-agrofood": HTMLUtrechtIconMonitorAgrofoodElement;
        "utrecht-icon-monitor-duurzaamheid": HTMLUtrechtIconMonitorDuurzaamheidElement;
        "utrecht-icon-monitor-sociaal": HTMLUtrechtIconMonitorSociaalElement;
        "utrecht-icon-monitor-virus": HTMLUtrechtIconMonitorVirusElement;
        "utrecht-icon-monitor-woningmarkt": HTMLUtrechtIconMonitorWoningmarktElement;
        "utrecht-icon-natuur-landschap": HTMLUtrechtIconNatuurLandschapElement;
        "utrecht-icon-nieuwsbrief": HTMLUtrechtIconNieuwsbriefElement;
        "utrecht-icon-omgeving": HTMLUtrechtIconOmgevingElement;
        "utrecht-icon-omgevingsvergunning": HTMLUtrechtIconOmgevingsvergunningElement;
        "utrecht-icon-onderhoud": HTMLUtrechtIconOnderhoudElement;
        "utrecht-icon-ondernemen": HTMLUtrechtIconOndernemenElement;
        "utrecht-icon-onderscheidingen": HTMLUtrechtIconOnderscheidingenElement;
        "utrecht-icon-onderwijs": HTMLUtrechtIconOnderwijsElement;
        "utrecht-icon-openingstijden": HTMLUtrechtIconOpeningstijdenElement;
        "utrecht-icon-over-de-gemeente": HTMLUtrechtIconOverDeGemeenteElement;
        "utrecht-icon-over-de-stad": HTMLUtrechtIconOverDeStadElement;
        "utrecht-icon-parkeervoorziening-gehandicapten": HTMLUtrechtIconParkeervoorzieningGehandicaptenElement;
        "utrecht-icon-parkeren": HTMLUtrechtIconParkerenElement;
        "utrecht-icon-paspoort": HTMLUtrechtIconPaspoortElement;
        "utrecht-icon-paspoort-idkaart-gecombineerd": HTMLUtrechtIconPaspoortIdkaartGecombineerdElement;
        "utrecht-icon-prijskaartje": HTMLUtrechtIconPrijskaartjeElement;
        "utrecht-icon-raad-en-college": HTMLUtrechtIconRaadEnCollegeElement;
        "utrecht-icon-reclame": HTMLUtrechtIconReclameElement;
        "utrecht-icon-recreatie": HTMLUtrechtIconRecreatieElement;
        "utrecht-icon-regeling-laag-inkomen": HTMLUtrechtIconRegelingLaagInkomenElement;
        "utrecht-icon-rijbewijs": HTMLUtrechtIconRijbewijsElement;
        "utrecht-icon-schoolkostenregeling": HTMLUtrechtIconSchoolkostenregelingElement;
        "utrecht-icon-sinterklaas": HTMLUtrechtIconSinterklaasElement;
        "utrecht-icon-sociaal-zorg-welzijn": HTMLUtrechtIconSociaalZorgWelzijnElement;
        "utrecht-icon-sport": HTMLUtrechtIconSportElement;
        "utrecht-icon-sport-culturele-activiteit": HTMLUtrechtIconSportCultureleActiviteitElement;
        "utrecht-icon-sportkleding-muziekinstrumenten": HTMLUtrechtIconSportkledingMuziekinstrumentenElement;
        "utrecht-icon-station-sneltrein": HTMLUtrechtIconStationSneltreinElement;
        "utrecht-icon-station-stoptrein": HTMLUtrechtIconStationStoptreinElement;
        "utrecht-icon-stookverbod": HTMLUtrechtIconStookverbodElement;
        "utrecht-icon-strand": HTMLUtrechtIconStrandElement;
        "utrecht-icon-subsidie": HTMLUtrechtIconSubsidieElement;
        "utrecht-icon-temperatuur-melding": HTMLUtrechtIconTemperatuurMeldingElement;
        "utrecht-icon-trouwen-en-geregistreerd-partnerschap": HTMLUtrechtIconTrouwenEnGeregistreerdPartnerschapElement;
        "utrecht-icon-tuinbouw": HTMLUtrechtIconTuinbouwElement;
        "utrecht-icon-uittreksel": HTMLUtrechtIconUittrekselElement;
        "utrecht-icon-uw-gemeente": HTMLUtrechtIconUwGemeenteElement;
        "utrecht-icon-uw-wijk": HTMLUtrechtIconUwWijkElement;
        "utrecht-icon-vacatures": HTMLUtrechtIconVacaturesElement;
        "utrecht-icon-veerboot": HTMLUtrechtIconVeerbootElement;
        "utrecht-icon-veilige-wijk": HTMLUtrechtIconVeiligeWijkElement;
        "utrecht-icon-vergaderen": HTMLUtrechtIconVergaderenElement;
        "utrecht-icon-vergunning-algemeen": HTMLUtrechtIconVergunningAlgemeenElement;
        "utrecht-icon-verhuizen": HTMLUtrechtIconVerhuizenElement;
        "utrecht-icon-verkiezingen": HTMLUtrechtIconVerkiezingenElement;
        "utrecht-icon-vervoersvoorziening": HTMLUtrechtIconVervoersvoorzieningElement;
        "utrecht-icon-virus": HTMLUtrechtIconVirusElement;
        "utrecht-icon-vluchtelingen-opvang": HTMLUtrechtIconVluchtelingenOpvangElement;
        "utrecht-icon-voeding": HTMLUtrechtIconVoedingElement;
        "utrecht-icon-vrijwilligerswerk": HTMLUtrechtIconVrijwilligerswerkElement;
        "utrecht-icon-vuurwerk": HTMLUtrechtIconVuurwerkElement;
        "utrecht-icon-wandelen": HTMLUtrechtIconWandelenElement;
        "utrecht-icon-werkzaamheden": HTMLUtrechtIconWerkzaamhedenElement;
        "utrecht-icon-wijkteam": HTMLUtrechtIconWijkteamElement;
        "utrecht-icon-winkelen": HTMLUtrechtIconWinkelenElement;
        "utrecht-icon-winkelwagen": HTMLUtrechtIconWinkelwagenElement;
        "utrecht-icon-wmo": HTMLUtrechtIconWmoElement;
        "utrecht-icon-woz-waarde": HTMLUtrechtIconWozWaardeElement;
        "utrecht-icon-zwemabonnement": HTMLUtrechtIconZwemabonnementElement;
    }
}
declare namespace LocalJSX {
    interface UtrechtIconActueel {
    }
    interface UtrechtIconAfval {
    }
    interface UtrechtIconAfvalContainer {
    }
    interface UtrechtIconAfvalOphaal {
    }
    interface UtrechtIconAfvalScheiden {
    }
    interface UtrechtIconAfvalkalender {
    }
    interface UtrechtIconAgenda {
    }
    interface UtrechtIconAirborne {
    }
    interface UtrechtIconAttentie {
    }
    interface UtrechtIconAuto {
    }
    interface UtrechtIconBedrijventerrein {
    }
    interface UtrechtIconBegroting {
    }
    interface UtrechtIconBelastingen {
    }
    interface UtrechtIconBevolking {
    }
    interface UtrechtIconBevrijding {
    }
    interface UtrechtIconBezwaarEnBeroep {
    }
    interface UtrechtIconBijstandsuitkering {
    }
    interface UtrechtIconBladerenOpruimen {
    }
    interface UtrechtIconBouwenEnVerbouwen {
    }
    interface UtrechtIconBrandgevaar {
    }
    interface UtrechtIconBuitengebied {
    }
    interface UtrechtIconComputerregeling {
    }
    interface UtrechtIconContactGemeente {
    }
    interface UtrechtIconContainer {
    }
    interface UtrechtIconDocumenten {
    }
    interface UtrechtIconDuurzaamheid {
    }
    interface UtrechtIconEconomieWerkInkomen {
    }
    interface UtrechtIconEikenprocessie {
    }
    interface UtrechtIconEnergietransitie {
    }
    interface UtrechtIconEvenementen {
    }
    interface UtrechtIconF1 {
    }
    interface UtrechtIconFiets {
    }
    interface UtrechtIconGebruikerCentraal {
    }
    interface UtrechtIconGebruikerIngelogd {
    }
    interface UtrechtIconGebruikersvraag {
    }
    interface UtrechtIconGemeenteraad {
    }
    interface UtrechtIconGemivaLocatie {
    }
    interface UtrechtIconGezicht {
    }
    interface UtrechtIconGladheid {
    }
    interface UtrechtIconGrafiek {
    }
    interface UtrechtIconGrofvuil {
    }
    interface UtrechtIconHondenbelasting {
    }
    interface UtrechtIconHorecavergunningen {
    }
    interface UtrechtIconHuis {
    }
    interface UtrechtIconHuisEnOmgeving {
    }
    interface UtrechtIconHulpmiddelenVinden {
    }
    interface UtrechtIconIdkaart {
    }
    interface UtrechtIconInEnOmUwHuis {
    }
    interface UtrechtIconInformatie {
    }
    interface UtrechtIconInformatieEnBetalen {
    }
    interface UtrechtIconInkomen {
    }
    interface UtrechtIconJeugd {
    }
    interface UtrechtIconKerstbomen {
    }
    interface UtrechtIconKindEnFamilie {
    }
    interface UtrechtIconKoningsdag {
    }
    interface UtrechtIconKopenEnHuren {
    }
    interface UtrechtIconKopenEnVerkopen {
    }
    interface UtrechtIconLeerlingenvervoer {
    }
    interface UtrechtIconLetOp {
    }
    interface UtrechtIconLiefdadigheid {
    }
    interface UtrechtIconLocatie {
    }
    interface UtrechtIconManege {
    }
    interface UtrechtIconMeeuwenoverlast {
    }
    interface UtrechtIconMelding {
    }
    interface UtrechtIconMeldingOpenbareRuimte {
    }
    interface UtrechtIconMobiliteit {
    }
    interface UtrechtIconMonitorAgrofood {
    }
    interface UtrechtIconMonitorDuurzaamheid {
    }
    interface UtrechtIconMonitorSociaal {
    }
    interface UtrechtIconMonitorVirus {
    }
    interface UtrechtIconMonitorWoningmarkt {
    }
    interface UtrechtIconNatuurLandschap {
    }
    interface UtrechtIconNieuwsbrief {
    }
    interface UtrechtIconOmgeving {
    }
    interface UtrechtIconOmgevingsvergunning {
    }
    interface UtrechtIconOnderhoud {
    }
    interface UtrechtIconOndernemen {
    }
    interface UtrechtIconOnderscheidingen {
    }
    interface UtrechtIconOnderwijs {
    }
    interface UtrechtIconOpeningstijden {
    }
    interface UtrechtIconOverDeGemeente {
    }
    interface UtrechtIconOverDeStad {
    }
    interface UtrechtIconParkeervoorzieningGehandicapten {
    }
    interface UtrechtIconParkeren {
    }
    interface UtrechtIconPaspoort {
    }
    interface UtrechtIconPaspoortIdkaartGecombineerd {
    }
    interface UtrechtIconPrijskaartje {
    }
    interface UtrechtIconRaadEnCollege {
    }
    interface UtrechtIconReclame {
    }
    interface UtrechtIconRecreatie {
    }
    interface UtrechtIconRegelingLaagInkomen {
    }
    interface UtrechtIconRijbewijs {
    }
    interface UtrechtIconSchoolkostenregeling {
    }
    interface UtrechtIconSinterklaas {
    }
    interface UtrechtIconSociaalZorgWelzijn {
    }
    interface UtrechtIconSport {
    }
    interface UtrechtIconSportCultureleActiviteit {
    }
    interface UtrechtIconSportkledingMuziekinstrumenten {
    }
    interface UtrechtIconStationSneltrein {
    }
    interface UtrechtIconStationStoptrein {
    }
    interface UtrechtIconStookverbod {
    }
    interface UtrechtIconStrand {
    }
    interface UtrechtIconSubsidie {
    }
    interface UtrechtIconTemperatuurMelding {
    }
    interface UtrechtIconTrouwenEnGeregistreerdPartnerschap {
    }
    interface UtrechtIconTuinbouw {
    }
    interface UtrechtIconUittreksel {
    }
    interface UtrechtIconUwGemeente {
    }
    interface UtrechtIconUwWijk {
    }
    interface UtrechtIconVacatures {
    }
    interface UtrechtIconVeerboot {
    }
    interface UtrechtIconVeiligeWijk {
    }
    interface UtrechtIconVergaderen {
    }
    interface UtrechtIconVergunningAlgemeen {
    }
    interface UtrechtIconVerhuizen {
    }
    interface UtrechtIconVerkiezingen {
    }
    interface UtrechtIconVervoersvoorziening {
    }
    interface UtrechtIconVirus {
    }
    interface UtrechtIconVluchtelingenOpvang {
    }
    interface UtrechtIconVoeding {
    }
    interface UtrechtIconVrijwilligerswerk {
    }
    interface UtrechtIconVuurwerk {
    }
    interface UtrechtIconWandelen {
    }
    interface UtrechtIconWerkzaamheden {
    }
    interface UtrechtIconWijkteam {
    }
    interface UtrechtIconWinkelen {
    }
    interface UtrechtIconWinkelwagen {
    }
    interface UtrechtIconWmo {
    }
    interface UtrechtIconWozWaarde {
    }
    interface UtrechtIconZwemabonnement {
    }
    interface IntrinsicElements {
        "utrecht-icon-actueel": UtrechtIconActueel;
        "utrecht-icon-afval": UtrechtIconAfval;
        "utrecht-icon-afval-container": UtrechtIconAfvalContainer;
        "utrecht-icon-afval-ophaal": UtrechtIconAfvalOphaal;
        "utrecht-icon-afval-scheiden": UtrechtIconAfvalScheiden;
        "utrecht-icon-afvalkalender": UtrechtIconAfvalkalender;
        "utrecht-icon-agenda": UtrechtIconAgenda;
        "utrecht-icon-airborne": UtrechtIconAirborne;
        "utrecht-icon-attentie": UtrechtIconAttentie;
        "utrecht-icon-auto": UtrechtIconAuto;
        "utrecht-icon-bedrijventerrein": UtrechtIconBedrijventerrein;
        "utrecht-icon-begroting": UtrechtIconBegroting;
        "utrecht-icon-belastingen": UtrechtIconBelastingen;
        "utrecht-icon-bevolking": UtrechtIconBevolking;
        "utrecht-icon-bevrijding": UtrechtIconBevrijding;
        "utrecht-icon-bezwaar-en-beroep": UtrechtIconBezwaarEnBeroep;
        "utrecht-icon-bijstandsuitkering": UtrechtIconBijstandsuitkering;
        "utrecht-icon-bladeren-opruimen": UtrechtIconBladerenOpruimen;
        "utrecht-icon-bouwen-en-verbouwen": UtrechtIconBouwenEnVerbouwen;
        "utrecht-icon-brandgevaar": UtrechtIconBrandgevaar;
        "utrecht-icon-buitengebied": UtrechtIconBuitengebied;
        "utrecht-icon-computerregeling": UtrechtIconComputerregeling;
        "utrecht-icon-contact-gemeente": UtrechtIconContactGemeente;
        "utrecht-icon-container": UtrechtIconContainer;
        "utrecht-icon-documenten": UtrechtIconDocumenten;
        "utrecht-icon-duurzaamheid": UtrechtIconDuurzaamheid;
        "utrecht-icon-economie-werk-inkomen": UtrechtIconEconomieWerkInkomen;
        "utrecht-icon-eikenprocessie": UtrechtIconEikenprocessie;
        "utrecht-icon-energietransitie": UtrechtIconEnergietransitie;
        "utrecht-icon-evenementen": UtrechtIconEvenementen;
        "utrecht-icon-f-1": UtrechtIconF1;
        "utrecht-icon-fiets": UtrechtIconFiets;
        "utrecht-icon-gebruiker-centraal": UtrechtIconGebruikerCentraal;
        "utrecht-icon-gebruiker-ingelogd": UtrechtIconGebruikerIngelogd;
        "utrecht-icon-gebruikersvraag": UtrechtIconGebruikersvraag;
        "utrecht-icon-gemeenteraad": UtrechtIconGemeenteraad;
        "utrecht-icon-gemiva-locatie": UtrechtIconGemivaLocatie;
        "utrecht-icon-gezicht": UtrechtIconGezicht;
        "utrecht-icon-gladheid": UtrechtIconGladheid;
        "utrecht-icon-grafiek": UtrechtIconGrafiek;
        "utrecht-icon-grofvuil": UtrechtIconGrofvuil;
        "utrecht-icon-hondenbelasting": UtrechtIconHondenbelasting;
        "utrecht-icon-horecavergunningen": UtrechtIconHorecavergunningen;
        "utrecht-icon-huis": UtrechtIconHuis;
        "utrecht-icon-huis-en-omgeving": UtrechtIconHuisEnOmgeving;
        "utrecht-icon-hulpmiddelen-vinden": UtrechtIconHulpmiddelenVinden;
        "utrecht-icon-idkaart": UtrechtIconIdkaart;
        "utrecht-icon-in-en-om-uw-huis": UtrechtIconInEnOmUwHuis;
        "utrecht-icon-informatie": UtrechtIconInformatie;
        "utrecht-icon-informatie-en-betalen": UtrechtIconInformatieEnBetalen;
        "utrecht-icon-inkomen": UtrechtIconInkomen;
        "utrecht-icon-jeugd": UtrechtIconJeugd;
        "utrecht-icon-kerstbomen": UtrechtIconKerstbomen;
        "utrecht-icon-kind-en-familie": UtrechtIconKindEnFamilie;
        "utrecht-icon-koningsdag": UtrechtIconKoningsdag;
        "utrecht-icon-kopen-en-huren": UtrechtIconKopenEnHuren;
        "utrecht-icon-kopen-en-verkopen": UtrechtIconKopenEnVerkopen;
        "utrecht-icon-leerlingenvervoer": UtrechtIconLeerlingenvervoer;
        "utrecht-icon-let-op": UtrechtIconLetOp;
        "utrecht-icon-liefdadigheid": UtrechtIconLiefdadigheid;
        "utrecht-icon-locatie": UtrechtIconLocatie;
        "utrecht-icon-manege": UtrechtIconManege;
        "utrecht-icon-meeuwenoverlast": UtrechtIconMeeuwenoverlast;
        "utrecht-icon-melding": UtrechtIconMelding;
        "utrecht-icon-melding-openbare-ruimte": UtrechtIconMeldingOpenbareRuimte;
        "utrecht-icon-mobiliteit": UtrechtIconMobiliteit;
        "utrecht-icon-monitor-agrofood": UtrechtIconMonitorAgrofood;
        "utrecht-icon-monitor-duurzaamheid": UtrechtIconMonitorDuurzaamheid;
        "utrecht-icon-monitor-sociaal": UtrechtIconMonitorSociaal;
        "utrecht-icon-monitor-virus": UtrechtIconMonitorVirus;
        "utrecht-icon-monitor-woningmarkt": UtrechtIconMonitorWoningmarkt;
        "utrecht-icon-natuur-landschap": UtrechtIconNatuurLandschap;
        "utrecht-icon-nieuwsbrief": UtrechtIconNieuwsbrief;
        "utrecht-icon-omgeving": UtrechtIconOmgeving;
        "utrecht-icon-omgevingsvergunning": UtrechtIconOmgevingsvergunning;
        "utrecht-icon-onderhoud": UtrechtIconOnderhoud;
        "utrecht-icon-ondernemen": UtrechtIconOndernemen;
        "utrecht-icon-onderscheidingen": UtrechtIconOnderscheidingen;
        "utrecht-icon-onderwijs": UtrechtIconOnderwijs;
        "utrecht-icon-openingstijden": UtrechtIconOpeningstijden;
        "utrecht-icon-over-de-gemeente": UtrechtIconOverDeGemeente;
        "utrecht-icon-over-de-stad": UtrechtIconOverDeStad;
        "utrecht-icon-parkeervoorziening-gehandicapten": UtrechtIconParkeervoorzieningGehandicapten;
        "utrecht-icon-parkeren": UtrechtIconParkeren;
        "utrecht-icon-paspoort": UtrechtIconPaspoort;
        "utrecht-icon-paspoort-idkaart-gecombineerd": UtrechtIconPaspoortIdkaartGecombineerd;
        "utrecht-icon-prijskaartje": UtrechtIconPrijskaartje;
        "utrecht-icon-raad-en-college": UtrechtIconRaadEnCollege;
        "utrecht-icon-reclame": UtrechtIconReclame;
        "utrecht-icon-recreatie": UtrechtIconRecreatie;
        "utrecht-icon-regeling-laag-inkomen": UtrechtIconRegelingLaagInkomen;
        "utrecht-icon-rijbewijs": UtrechtIconRijbewijs;
        "utrecht-icon-schoolkostenregeling": UtrechtIconSchoolkostenregeling;
        "utrecht-icon-sinterklaas": UtrechtIconSinterklaas;
        "utrecht-icon-sociaal-zorg-welzijn": UtrechtIconSociaalZorgWelzijn;
        "utrecht-icon-sport": UtrechtIconSport;
        "utrecht-icon-sport-culturele-activiteit": UtrechtIconSportCultureleActiviteit;
        "utrecht-icon-sportkleding-muziekinstrumenten": UtrechtIconSportkledingMuziekinstrumenten;
        "utrecht-icon-station-sneltrein": UtrechtIconStationSneltrein;
        "utrecht-icon-station-stoptrein": UtrechtIconStationStoptrein;
        "utrecht-icon-stookverbod": UtrechtIconStookverbod;
        "utrecht-icon-strand": UtrechtIconStrand;
        "utrecht-icon-subsidie": UtrechtIconSubsidie;
        "utrecht-icon-temperatuur-melding": UtrechtIconTemperatuurMelding;
        "utrecht-icon-trouwen-en-geregistreerd-partnerschap": UtrechtIconTrouwenEnGeregistreerdPartnerschap;
        "utrecht-icon-tuinbouw": UtrechtIconTuinbouw;
        "utrecht-icon-uittreksel": UtrechtIconUittreksel;
        "utrecht-icon-uw-gemeente": UtrechtIconUwGemeente;
        "utrecht-icon-uw-wijk": UtrechtIconUwWijk;
        "utrecht-icon-vacatures": UtrechtIconVacatures;
        "utrecht-icon-veerboot": UtrechtIconVeerboot;
        "utrecht-icon-veilige-wijk": UtrechtIconVeiligeWijk;
        "utrecht-icon-vergaderen": UtrechtIconVergaderen;
        "utrecht-icon-vergunning-algemeen": UtrechtIconVergunningAlgemeen;
        "utrecht-icon-verhuizen": UtrechtIconVerhuizen;
        "utrecht-icon-verkiezingen": UtrechtIconVerkiezingen;
        "utrecht-icon-vervoersvoorziening": UtrechtIconVervoersvoorziening;
        "utrecht-icon-virus": UtrechtIconVirus;
        "utrecht-icon-vluchtelingen-opvang": UtrechtIconVluchtelingenOpvang;
        "utrecht-icon-voeding": UtrechtIconVoeding;
        "utrecht-icon-vrijwilligerswerk": UtrechtIconVrijwilligerswerk;
        "utrecht-icon-vuurwerk": UtrechtIconVuurwerk;
        "utrecht-icon-wandelen": UtrechtIconWandelen;
        "utrecht-icon-werkzaamheden": UtrechtIconWerkzaamheden;
        "utrecht-icon-wijkteam": UtrechtIconWijkteam;
        "utrecht-icon-winkelen": UtrechtIconWinkelen;
        "utrecht-icon-winkelwagen": UtrechtIconWinkelwagen;
        "utrecht-icon-wmo": UtrechtIconWmo;
        "utrecht-icon-woz-waarde": UtrechtIconWozWaarde;
        "utrecht-icon-zwemabonnement": UtrechtIconZwemabonnement;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "utrecht-icon-actueel": LocalJSX.UtrechtIconActueel & JSXBase.HTMLAttributes<HTMLUtrechtIconActueelElement>;
            "utrecht-icon-afval": LocalJSX.UtrechtIconAfval & JSXBase.HTMLAttributes<HTMLUtrechtIconAfvalElement>;
            "utrecht-icon-afval-container": LocalJSX.UtrechtIconAfvalContainer & JSXBase.HTMLAttributes<HTMLUtrechtIconAfvalContainerElement>;
            "utrecht-icon-afval-ophaal": LocalJSX.UtrechtIconAfvalOphaal & JSXBase.HTMLAttributes<HTMLUtrechtIconAfvalOphaalElement>;
            "utrecht-icon-afval-scheiden": LocalJSX.UtrechtIconAfvalScheiden & JSXBase.HTMLAttributes<HTMLUtrechtIconAfvalScheidenElement>;
            "utrecht-icon-afvalkalender": LocalJSX.UtrechtIconAfvalkalender & JSXBase.HTMLAttributes<HTMLUtrechtIconAfvalkalenderElement>;
            "utrecht-icon-agenda": LocalJSX.UtrechtIconAgenda & JSXBase.HTMLAttributes<HTMLUtrechtIconAgendaElement>;
            "utrecht-icon-airborne": LocalJSX.UtrechtIconAirborne & JSXBase.HTMLAttributes<HTMLUtrechtIconAirborneElement>;
            "utrecht-icon-attentie": LocalJSX.UtrechtIconAttentie & JSXBase.HTMLAttributes<HTMLUtrechtIconAttentieElement>;
            "utrecht-icon-auto": LocalJSX.UtrechtIconAuto & JSXBase.HTMLAttributes<HTMLUtrechtIconAutoElement>;
            "utrecht-icon-bedrijventerrein": LocalJSX.UtrechtIconBedrijventerrein & JSXBase.HTMLAttributes<HTMLUtrechtIconBedrijventerreinElement>;
            "utrecht-icon-begroting": LocalJSX.UtrechtIconBegroting & JSXBase.HTMLAttributes<HTMLUtrechtIconBegrotingElement>;
            "utrecht-icon-belastingen": LocalJSX.UtrechtIconBelastingen & JSXBase.HTMLAttributes<HTMLUtrechtIconBelastingenElement>;
            "utrecht-icon-bevolking": LocalJSX.UtrechtIconBevolking & JSXBase.HTMLAttributes<HTMLUtrechtIconBevolkingElement>;
            "utrecht-icon-bevrijding": LocalJSX.UtrechtIconBevrijding & JSXBase.HTMLAttributes<HTMLUtrechtIconBevrijdingElement>;
            "utrecht-icon-bezwaar-en-beroep": LocalJSX.UtrechtIconBezwaarEnBeroep & JSXBase.HTMLAttributes<HTMLUtrechtIconBezwaarEnBeroepElement>;
            "utrecht-icon-bijstandsuitkering": LocalJSX.UtrechtIconBijstandsuitkering & JSXBase.HTMLAttributes<HTMLUtrechtIconBijstandsuitkeringElement>;
            "utrecht-icon-bladeren-opruimen": LocalJSX.UtrechtIconBladerenOpruimen & JSXBase.HTMLAttributes<HTMLUtrechtIconBladerenOpruimenElement>;
            "utrecht-icon-bouwen-en-verbouwen": LocalJSX.UtrechtIconBouwenEnVerbouwen & JSXBase.HTMLAttributes<HTMLUtrechtIconBouwenEnVerbouwenElement>;
            "utrecht-icon-brandgevaar": LocalJSX.UtrechtIconBrandgevaar & JSXBase.HTMLAttributes<HTMLUtrechtIconBrandgevaarElement>;
            "utrecht-icon-buitengebied": LocalJSX.UtrechtIconBuitengebied & JSXBase.HTMLAttributes<HTMLUtrechtIconBuitengebiedElement>;
            "utrecht-icon-computerregeling": LocalJSX.UtrechtIconComputerregeling & JSXBase.HTMLAttributes<HTMLUtrechtIconComputerregelingElement>;
            "utrecht-icon-contact-gemeente": LocalJSX.UtrechtIconContactGemeente & JSXBase.HTMLAttributes<HTMLUtrechtIconContactGemeenteElement>;
            "utrecht-icon-container": LocalJSX.UtrechtIconContainer & JSXBase.HTMLAttributes<HTMLUtrechtIconContainerElement>;
            "utrecht-icon-documenten": LocalJSX.UtrechtIconDocumenten & JSXBase.HTMLAttributes<HTMLUtrechtIconDocumentenElement>;
            "utrecht-icon-duurzaamheid": LocalJSX.UtrechtIconDuurzaamheid & JSXBase.HTMLAttributes<HTMLUtrechtIconDuurzaamheidElement>;
            "utrecht-icon-economie-werk-inkomen": LocalJSX.UtrechtIconEconomieWerkInkomen & JSXBase.HTMLAttributes<HTMLUtrechtIconEconomieWerkInkomenElement>;
            "utrecht-icon-eikenprocessie": LocalJSX.UtrechtIconEikenprocessie & JSXBase.HTMLAttributes<HTMLUtrechtIconEikenprocessieElement>;
            "utrecht-icon-energietransitie": LocalJSX.UtrechtIconEnergietransitie & JSXBase.HTMLAttributes<HTMLUtrechtIconEnergietransitieElement>;
            "utrecht-icon-evenementen": LocalJSX.UtrechtIconEvenementen & JSXBase.HTMLAttributes<HTMLUtrechtIconEvenementenElement>;
            "utrecht-icon-f-1": LocalJSX.UtrechtIconF1 & JSXBase.HTMLAttributes<HTMLUtrechtIconF1Element>;
            "utrecht-icon-fiets": LocalJSX.UtrechtIconFiets & JSXBase.HTMLAttributes<HTMLUtrechtIconFietsElement>;
            "utrecht-icon-gebruiker-centraal": LocalJSX.UtrechtIconGebruikerCentraal & JSXBase.HTMLAttributes<HTMLUtrechtIconGebruikerCentraalElement>;
            "utrecht-icon-gebruiker-ingelogd": LocalJSX.UtrechtIconGebruikerIngelogd & JSXBase.HTMLAttributes<HTMLUtrechtIconGebruikerIngelogdElement>;
            "utrecht-icon-gebruikersvraag": LocalJSX.UtrechtIconGebruikersvraag & JSXBase.HTMLAttributes<HTMLUtrechtIconGebruikersvraagElement>;
            "utrecht-icon-gemeenteraad": LocalJSX.UtrechtIconGemeenteraad & JSXBase.HTMLAttributes<HTMLUtrechtIconGemeenteraadElement>;
            "utrecht-icon-gemiva-locatie": LocalJSX.UtrechtIconGemivaLocatie & JSXBase.HTMLAttributes<HTMLUtrechtIconGemivaLocatieElement>;
            "utrecht-icon-gezicht": LocalJSX.UtrechtIconGezicht & JSXBase.HTMLAttributes<HTMLUtrechtIconGezichtElement>;
            "utrecht-icon-gladheid": LocalJSX.UtrechtIconGladheid & JSXBase.HTMLAttributes<HTMLUtrechtIconGladheidElement>;
            "utrecht-icon-grafiek": LocalJSX.UtrechtIconGrafiek & JSXBase.HTMLAttributes<HTMLUtrechtIconGrafiekElement>;
            "utrecht-icon-grofvuil": LocalJSX.UtrechtIconGrofvuil & JSXBase.HTMLAttributes<HTMLUtrechtIconGrofvuilElement>;
            "utrecht-icon-hondenbelasting": LocalJSX.UtrechtIconHondenbelasting & JSXBase.HTMLAttributes<HTMLUtrechtIconHondenbelastingElement>;
            "utrecht-icon-horecavergunningen": LocalJSX.UtrechtIconHorecavergunningen & JSXBase.HTMLAttributes<HTMLUtrechtIconHorecavergunningenElement>;
            "utrecht-icon-huis": LocalJSX.UtrechtIconHuis & JSXBase.HTMLAttributes<HTMLUtrechtIconHuisElement>;
            "utrecht-icon-huis-en-omgeving": LocalJSX.UtrechtIconHuisEnOmgeving & JSXBase.HTMLAttributes<HTMLUtrechtIconHuisEnOmgevingElement>;
            "utrecht-icon-hulpmiddelen-vinden": LocalJSX.UtrechtIconHulpmiddelenVinden & JSXBase.HTMLAttributes<HTMLUtrechtIconHulpmiddelenVindenElement>;
            "utrecht-icon-idkaart": LocalJSX.UtrechtIconIdkaart & JSXBase.HTMLAttributes<HTMLUtrechtIconIdkaartElement>;
            "utrecht-icon-in-en-om-uw-huis": LocalJSX.UtrechtIconInEnOmUwHuis & JSXBase.HTMLAttributes<HTMLUtrechtIconInEnOmUwHuisElement>;
            "utrecht-icon-informatie": LocalJSX.UtrechtIconInformatie & JSXBase.HTMLAttributes<HTMLUtrechtIconInformatieElement>;
            "utrecht-icon-informatie-en-betalen": LocalJSX.UtrechtIconInformatieEnBetalen & JSXBase.HTMLAttributes<HTMLUtrechtIconInformatieEnBetalenElement>;
            "utrecht-icon-inkomen": LocalJSX.UtrechtIconInkomen & JSXBase.HTMLAttributes<HTMLUtrechtIconInkomenElement>;
            "utrecht-icon-jeugd": LocalJSX.UtrechtIconJeugd & JSXBase.HTMLAttributes<HTMLUtrechtIconJeugdElement>;
            "utrecht-icon-kerstbomen": LocalJSX.UtrechtIconKerstbomen & JSXBase.HTMLAttributes<HTMLUtrechtIconKerstbomenElement>;
            "utrecht-icon-kind-en-familie": LocalJSX.UtrechtIconKindEnFamilie & JSXBase.HTMLAttributes<HTMLUtrechtIconKindEnFamilieElement>;
            "utrecht-icon-koningsdag": LocalJSX.UtrechtIconKoningsdag & JSXBase.HTMLAttributes<HTMLUtrechtIconKoningsdagElement>;
            "utrecht-icon-kopen-en-huren": LocalJSX.UtrechtIconKopenEnHuren & JSXBase.HTMLAttributes<HTMLUtrechtIconKopenEnHurenElement>;
            "utrecht-icon-kopen-en-verkopen": LocalJSX.UtrechtIconKopenEnVerkopen & JSXBase.HTMLAttributes<HTMLUtrechtIconKopenEnVerkopenElement>;
            "utrecht-icon-leerlingenvervoer": LocalJSX.UtrechtIconLeerlingenvervoer & JSXBase.HTMLAttributes<HTMLUtrechtIconLeerlingenvervoerElement>;
            "utrecht-icon-let-op": LocalJSX.UtrechtIconLetOp & JSXBase.HTMLAttributes<HTMLUtrechtIconLetOpElement>;
            "utrecht-icon-liefdadigheid": LocalJSX.UtrechtIconLiefdadigheid & JSXBase.HTMLAttributes<HTMLUtrechtIconLiefdadigheidElement>;
            "utrecht-icon-locatie": LocalJSX.UtrechtIconLocatie & JSXBase.HTMLAttributes<HTMLUtrechtIconLocatieElement>;
            "utrecht-icon-manege": LocalJSX.UtrechtIconManege & JSXBase.HTMLAttributes<HTMLUtrechtIconManegeElement>;
            "utrecht-icon-meeuwenoverlast": LocalJSX.UtrechtIconMeeuwenoverlast & JSXBase.HTMLAttributes<HTMLUtrechtIconMeeuwenoverlastElement>;
            "utrecht-icon-melding": LocalJSX.UtrechtIconMelding & JSXBase.HTMLAttributes<HTMLUtrechtIconMeldingElement>;
            "utrecht-icon-melding-openbare-ruimte": LocalJSX.UtrechtIconMeldingOpenbareRuimte & JSXBase.HTMLAttributes<HTMLUtrechtIconMeldingOpenbareRuimteElement>;
            "utrecht-icon-mobiliteit": LocalJSX.UtrechtIconMobiliteit & JSXBase.HTMLAttributes<HTMLUtrechtIconMobiliteitElement>;
            "utrecht-icon-monitor-agrofood": LocalJSX.UtrechtIconMonitorAgrofood & JSXBase.HTMLAttributes<HTMLUtrechtIconMonitorAgrofoodElement>;
            "utrecht-icon-monitor-duurzaamheid": LocalJSX.UtrechtIconMonitorDuurzaamheid & JSXBase.HTMLAttributes<HTMLUtrechtIconMonitorDuurzaamheidElement>;
            "utrecht-icon-monitor-sociaal": LocalJSX.UtrechtIconMonitorSociaal & JSXBase.HTMLAttributes<HTMLUtrechtIconMonitorSociaalElement>;
            "utrecht-icon-monitor-virus": LocalJSX.UtrechtIconMonitorVirus & JSXBase.HTMLAttributes<HTMLUtrechtIconMonitorVirusElement>;
            "utrecht-icon-monitor-woningmarkt": LocalJSX.UtrechtIconMonitorWoningmarkt & JSXBase.HTMLAttributes<HTMLUtrechtIconMonitorWoningmarktElement>;
            "utrecht-icon-natuur-landschap": LocalJSX.UtrechtIconNatuurLandschap & JSXBase.HTMLAttributes<HTMLUtrechtIconNatuurLandschapElement>;
            "utrecht-icon-nieuwsbrief": LocalJSX.UtrechtIconNieuwsbrief & JSXBase.HTMLAttributes<HTMLUtrechtIconNieuwsbriefElement>;
            "utrecht-icon-omgeving": LocalJSX.UtrechtIconOmgeving & JSXBase.HTMLAttributes<HTMLUtrechtIconOmgevingElement>;
            "utrecht-icon-omgevingsvergunning": LocalJSX.UtrechtIconOmgevingsvergunning & JSXBase.HTMLAttributes<HTMLUtrechtIconOmgevingsvergunningElement>;
            "utrecht-icon-onderhoud": LocalJSX.UtrechtIconOnderhoud & JSXBase.HTMLAttributes<HTMLUtrechtIconOnderhoudElement>;
            "utrecht-icon-ondernemen": LocalJSX.UtrechtIconOndernemen & JSXBase.HTMLAttributes<HTMLUtrechtIconOndernemenElement>;
            "utrecht-icon-onderscheidingen": LocalJSX.UtrechtIconOnderscheidingen & JSXBase.HTMLAttributes<HTMLUtrechtIconOnderscheidingenElement>;
            "utrecht-icon-onderwijs": LocalJSX.UtrechtIconOnderwijs & JSXBase.HTMLAttributes<HTMLUtrechtIconOnderwijsElement>;
            "utrecht-icon-openingstijden": LocalJSX.UtrechtIconOpeningstijden & JSXBase.HTMLAttributes<HTMLUtrechtIconOpeningstijdenElement>;
            "utrecht-icon-over-de-gemeente": LocalJSX.UtrechtIconOverDeGemeente & JSXBase.HTMLAttributes<HTMLUtrechtIconOverDeGemeenteElement>;
            "utrecht-icon-over-de-stad": LocalJSX.UtrechtIconOverDeStad & JSXBase.HTMLAttributes<HTMLUtrechtIconOverDeStadElement>;
            "utrecht-icon-parkeervoorziening-gehandicapten": LocalJSX.UtrechtIconParkeervoorzieningGehandicapten & JSXBase.HTMLAttributes<HTMLUtrechtIconParkeervoorzieningGehandicaptenElement>;
            "utrecht-icon-parkeren": LocalJSX.UtrechtIconParkeren & JSXBase.HTMLAttributes<HTMLUtrechtIconParkerenElement>;
            "utrecht-icon-paspoort": LocalJSX.UtrechtIconPaspoort & JSXBase.HTMLAttributes<HTMLUtrechtIconPaspoortElement>;
            "utrecht-icon-paspoort-idkaart-gecombineerd": LocalJSX.UtrechtIconPaspoortIdkaartGecombineerd & JSXBase.HTMLAttributes<HTMLUtrechtIconPaspoortIdkaartGecombineerdElement>;
            "utrecht-icon-prijskaartje": LocalJSX.UtrechtIconPrijskaartje & JSXBase.HTMLAttributes<HTMLUtrechtIconPrijskaartjeElement>;
            "utrecht-icon-raad-en-college": LocalJSX.UtrechtIconRaadEnCollege & JSXBase.HTMLAttributes<HTMLUtrechtIconRaadEnCollegeElement>;
            "utrecht-icon-reclame": LocalJSX.UtrechtIconReclame & JSXBase.HTMLAttributes<HTMLUtrechtIconReclameElement>;
            "utrecht-icon-recreatie": LocalJSX.UtrechtIconRecreatie & JSXBase.HTMLAttributes<HTMLUtrechtIconRecreatieElement>;
            "utrecht-icon-regeling-laag-inkomen": LocalJSX.UtrechtIconRegelingLaagInkomen & JSXBase.HTMLAttributes<HTMLUtrechtIconRegelingLaagInkomenElement>;
            "utrecht-icon-rijbewijs": LocalJSX.UtrechtIconRijbewijs & JSXBase.HTMLAttributes<HTMLUtrechtIconRijbewijsElement>;
            "utrecht-icon-schoolkostenregeling": LocalJSX.UtrechtIconSchoolkostenregeling & JSXBase.HTMLAttributes<HTMLUtrechtIconSchoolkostenregelingElement>;
            "utrecht-icon-sinterklaas": LocalJSX.UtrechtIconSinterklaas & JSXBase.HTMLAttributes<HTMLUtrechtIconSinterklaasElement>;
            "utrecht-icon-sociaal-zorg-welzijn": LocalJSX.UtrechtIconSociaalZorgWelzijn & JSXBase.HTMLAttributes<HTMLUtrechtIconSociaalZorgWelzijnElement>;
            "utrecht-icon-sport": LocalJSX.UtrechtIconSport & JSXBase.HTMLAttributes<HTMLUtrechtIconSportElement>;
            "utrecht-icon-sport-culturele-activiteit": LocalJSX.UtrechtIconSportCultureleActiviteit & JSXBase.HTMLAttributes<HTMLUtrechtIconSportCultureleActiviteitElement>;
            "utrecht-icon-sportkleding-muziekinstrumenten": LocalJSX.UtrechtIconSportkledingMuziekinstrumenten & JSXBase.HTMLAttributes<HTMLUtrechtIconSportkledingMuziekinstrumentenElement>;
            "utrecht-icon-station-sneltrein": LocalJSX.UtrechtIconStationSneltrein & JSXBase.HTMLAttributes<HTMLUtrechtIconStationSneltreinElement>;
            "utrecht-icon-station-stoptrein": LocalJSX.UtrechtIconStationStoptrein & JSXBase.HTMLAttributes<HTMLUtrechtIconStationStoptreinElement>;
            "utrecht-icon-stookverbod": LocalJSX.UtrechtIconStookverbod & JSXBase.HTMLAttributes<HTMLUtrechtIconStookverbodElement>;
            "utrecht-icon-strand": LocalJSX.UtrechtIconStrand & JSXBase.HTMLAttributes<HTMLUtrechtIconStrandElement>;
            "utrecht-icon-subsidie": LocalJSX.UtrechtIconSubsidie & JSXBase.HTMLAttributes<HTMLUtrechtIconSubsidieElement>;
            "utrecht-icon-temperatuur-melding": LocalJSX.UtrechtIconTemperatuurMelding & JSXBase.HTMLAttributes<HTMLUtrechtIconTemperatuurMeldingElement>;
            "utrecht-icon-trouwen-en-geregistreerd-partnerschap": LocalJSX.UtrechtIconTrouwenEnGeregistreerdPartnerschap & JSXBase.HTMLAttributes<HTMLUtrechtIconTrouwenEnGeregistreerdPartnerschapElement>;
            "utrecht-icon-tuinbouw": LocalJSX.UtrechtIconTuinbouw & JSXBase.HTMLAttributes<HTMLUtrechtIconTuinbouwElement>;
            "utrecht-icon-uittreksel": LocalJSX.UtrechtIconUittreksel & JSXBase.HTMLAttributes<HTMLUtrechtIconUittrekselElement>;
            "utrecht-icon-uw-gemeente": LocalJSX.UtrechtIconUwGemeente & JSXBase.HTMLAttributes<HTMLUtrechtIconUwGemeenteElement>;
            "utrecht-icon-uw-wijk": LocalJSX.UtrechtIconUwWijk & JSXBase.HTMLAttributes<HTMLUtrechtIconUwWijkElement>;
            "utrecht-icon-vacatures": LocalJSX.UtrechtIconVacatures & JSXBase.HTMLAttributes<HTMLUtrechtIconVacaturesElement>;
            "utrecht-icon-veerboot": LocalJSX.UtrechtIconVeerboot & JSXBase.HTMLAttributes<HTMLUtrechtIconVeerbootElement>;
            "utrecht-icon-veilige-wijk": LocalJSX.UtrechtIconVeiligeWijk & JSXBase.HTMLAttributes<HTMLUtrechtIconVeiligeWijkElement>;
            "utrecht-icon-vergaderen": LocalJSX.UtrechtIconVergaderen & JSXBase.HTMLAttributes<HTMLUtrechtIconVergaderenElement>;
            "utrecht-icon-vergunning-algemeen": LocalJSX.UtrechtIconVergunningAlgemeen & JSXBase.HTMLAttributes<HTMLUtrechtIconVergunningAlgemeenElement>;
            "utrecht-icon-verhuizen": LocalJSX.UtrechtIconVerhuizen & JSXBase.HTMLAttributes<HTMLUtrechtIconVerhuizenElement>;
            "utrecht-icon-verkiezingen": LocalJSX.UtrechtIconVerkiezingen & JSXBase.HTMLAttributes<HTMLUtrechtIconVerkiezingenElement>;
            "utrecht-icon-vervoersvoorziening": LocalJSX.UtrechtIconVervoersvoorziening & JSXBase.HTMLAttributes<HTMLUtrechtIconVervoersvoorzieningElement>;
            "utrecht-icon-virus": LocalJSX.UtrechtIconVirus & JSXBase.HTMLAttributes<HTMLUtrechtIconVirusElement>;
            "utrecht-icon-vluchtelingen-opvang": LocalJSX.UtrechtIconVluchtelingenOpvang & JSXBase.HTMLAttributes<HTMLUtrechtIconVluchtelingenOpvangElement>;
            "utrecht-icon-voeding": LocalJSX.UtrechtIconVoeding & JSXBase.HTMLAttributes<HTMLUtrechtIconVoedingElement>;
            "utrecht-icon-vrijwilligerswerk": LocalJSX.UtrechtIconVrijwilligerswerk & JSXBase.HTMLAttributes<HTMLUtrechtIconVrijwilligerswerkElement>;
            "utrecht-icon-vuurwerk": LocalJSX.UtrechtIconVuurwerk & JSXBase.HTMLAttributes<HTMLUtrechtIconVuurwerkElement>;
            "utrecht-icon-wandelen": LocalJSX.UtrechtIconWandelen & JSXBase.HTMLAttributes<HTMLUtrechtIconWandelenElement>;
            "utrecht-icon-werkzaamheden": LocalJSX.UtrechtIconWerkzaamheden & JSXBase.HTMLAttributes<HTMLUtrechtIconWerkzaamhedenElement>;
            "utrecht-icon-wijkteam": LocalJSX.UtrechtIconWijkteam & JSXBase.HTMLAttributes<HTMLUtrechtIconWijkteamElement>;
            "utrecht-icon-winkelen": LocalJSX.UtrechtIconWinkelen & JSXBase.HTMLAttributes<HTMLUtrechtIconWinkelenElement>;
            "utrecht-icon-winkelwagen": LocalJSX.UtrechtIconWinkelwagen & JSXBase.HTMLAttributes<HTMLUtrechtIconWinkelwagenElement>;
            "utrecht-icon-wmo": LocalJSX.UtrechtIconWmo & JSXBase.HTMLAttributes<HTMLUtrechtIconWmoElement>;
            "utrecht-icon-woz-waarde": LocalJSX.UtrechtIconWozWaarde & JSXBase.HTMLAttributes<HTMLUtrechtIconWozWaardeElement>;
            "utrecht-icon-zwemabonnement": LocalJSX.UtrechtIconZwemabonnement & JSXBase.HTMLAttributes<HTMLUtrechtIconZwemabonnementElement>;
        }
    }
}
