name: Release

on:
  push:
    branches: [main]
  pull_request:
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - name: Install semantic-release extra plugins
        run: npm i -D @semantic-release/changelog @semantic-release/git
      - name: Lint
        run: npm run lint-fix
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: packages/iconset-web-component/www/
      - name: Release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.ICON_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
          npm run release
          npm config delete "//registry.npmjs.org/:_authToken"
