name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@frameless"
      - run: npm ci
      - name: Install semantic-release extra plugins
        run: npm i -D @semantic-release/changelog @semantic-release/git
      - name: Lint
        run: npm run lint-fix
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
